### ISSUE TITLE
How to implement Polymorphic Relations ?

### ISSUE THREAD

**Issue by ebbbang** [Folkloreatelier/laravel-graphql#102]
How to use Polymorphic Type ?
E.g.

```php
public function fields()
{
    return [
       'id' => [
            'type' => Type::int(),
            'description' => 'The id of the Transaction',
        ],
        'transactable' => [
            'type' => // Here it can be CustomerWalletOrderType or CustomerTransferOrderType,
            'description' => 'Transaction responsible Model',
        ],
    ];
}
```

so how would you go about implementing this ?

**Comment by dmongeau** [comment]
You create an InterfaceType with a `resolveType` method that can return either `CustomerWalletOrderType` or `CustomerTransferOrderType` depending on the $root and then you set the type of `transactable` to this interface type.

**Comment by vladar** [comment]
`UnionType` is another option, but I don't know how you do it in `laravel-graphql`

**Comment by smallcar88** [comment]
Thanks @dmongeau ! I still have one problem, when creating Query, what should i put on `public function type()`? Here is my code: 
`public function type() {                                                                                                                                                                            
          return Type::listOf(GraphQL::type('UserInterface'));
 } `
There are `User` and `Seller` using `UserInterface` type, but the return is like this
`{"data":{"users":[[],[],[],[],[],[],[],[],[],[]]}}`

**Comment by dmongeau** [comment]
What is your query?
