### ISSUE TITLE
Multi filters Query

### ISSUE THREAD

**Issue by k4b0um** [Folkloreatelier/laravel-graphql#105]
Hi,

I would like to query graphQL with multi filters, like this

```
query Webhook {
  webhook(idWebsite: "123") {
    id
    events(name: "eventName") {
         id
    }
  }
}
```

Do you think that is possible ? And How declare fields ?

Actually, event name field is declared like that in webHookType:
```
public function fields()
    {
        return [
            ...
            'events' => [
                'args' => [
                    'name' => [
                        'type'        => Type::string(),
                        'description' => 'Name of the event',
                    ],
                ],
                'type'        => Type::listOf(GraphQL::type('Event')),
                'description' => 'Event subscription',
            ],
        ];
    }
```

I get only the webhookId  arg in resolver...

Thanks

**Comment by jsiebern** [comment]
Hi, I just needed the same thing and it should work fine if you use a field resolver in the webHookType.

Meaning something like this:

`public function resolveEventsField($root, $args) {
    if (isset($args['name'])) {
        return $root->events->where('name', $args['name']);
    }
    return $root->events;
}`
