### ISSUE TITLE
How can I deny mutation query in GET?

### ISSUE THREAD

**Issue by cesarzagonel** [Folkloreatelier/laravel-graphql#107]
Mutations query are accepted both in POST and GET.
How can I make it works just in POST?

**Comment by n1ru4l** [comment]
@cesarzagonel You will have to override/extend the [GraphQLController class](https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/config/config.php#L44). There you could check for the method of the mutation.

**Comment by dmongeau** [comment]
You could also set the `routes` param to null in the config and define the routes yourself
