### ISSUE TITLE
config_path fonction is not declared

### ISSUE THREAD

**Issue by SebastienFourreau** [Folkloreatelier/laravel-graphql#109]
Hi,

It seems to me that function `config_path` use in `Folklore\GraphQL\ServiceProvider` was never declared anywhere.

Nothing in the Laravel or Lumen framework.
Am i wrong ?

**Comment by NathanHeffley** [comment]
Are you trying to use this package in Laravel or Lumen? Or have you received the same error in both of them?

**Comment by SebastienFourreau** [comment]
I tried on Lumen, i manually add an helper with the function.

**Comment by NathanHeffley** [comment]
Did it work? If so, could you post the patch for what you did, or at least explain what you did and post the code for it and I'll create a patch?

**Comment by maxehhh** [comment]
@NathanHeffley here's the link i followed to patch the function.
[https://laravelista.com/posts/json-web-token-authentication-for-lumen](url)

**Comment by NathanHeffley** [comment]
Thanks @maxehhh!

**Comment by dmongeau** [comment]
Okay, I didn't know config_path was not part of Lumen. I will change it to `base_path('config')`. Can you confirm this will work?

**Comment by dmongeau** [comment]
Oh, just figured out that you should use the `Folklore\GraphQL\LumenServiceProvider` if you are using it with Lumen.
