### ISSUE TITLE
Add section to Advanved Usage

### ISSUE THREAD

**Issue by TheGhoul21** [Folkloreatelier/laravel-graphql#11]
I don't know how to create a pull request, to change the Readme.MD file.
I found how to use the [variables](https://facebook.github.io/graphql/#sec-Language.Document.Variables) feature documented.

It would be useful to add how to use parameters in the queries. 
Example:
```javascript
query myQuery($size:Int,$array:[String]){
    query(fields:$array){
        picture(size:$size),
        name
    }
}
```
and along with the query, there should be a `params` query field JSON-encoded

`www.[...]/graphql?query=[...]&params={size:10,array:["id1","id2","id3"]}`

and the `$args` parameter in the `resolve` function will be filled accordingly.

I would do it, but I have no idea of how pull requests work. I'm a GitHub n00b, sorry.

**Comment by dmongeau** [comment]
Done, thanks!
