### ISSUE TITLE
Relation snake_case vs camelCase

### ISSUE THREAD

**Issue by tremby** [Folkloreatelier/laravel-graphql#112]
I have a relation on my User model called `linkedSocialAccounts`.

When I set this up in the GraphQL `UserType` as `linkedSocialAccounts` (of type "list of LinkedSocialAccount") the data comes back as I expect it to.

But instead of `linkedSocialAccounts` I want to call this field `linked_social_accounts`, to match the other properties such as `provider_id` (which are working fine).

Must the name in the GraphQL type match the Eloquent relation name? Or is there some way to get around this?

I notice that in Tinker I can get the linked accounts via `$user->linkedSocialAccounts` but not via `$user->linked_social_accounts`, even though I can get `$user->createdAt` or `$user->created_at`, presumably due to some Laravel magic. But weirdly I can get `$linkedSocialAccount->provider_id` but not `$linkedSocialAccount->providerId` (this is not a magic getter method, it's just like `createdAt` on the other model as far as I know).

**Comment by dmongeau** [comment]
You can put anything you want as a GraphQL type name or fields name. If the name of a field is the same as the attribute/or relation of your eloquent model, it will resolve "automatically". In case there is a difference, you can use a resolve method.

```php
protected function fields()
{
    return [
        'linkedSocialAccounts' => [
            'type'=> //whatever type it is,
            'resolve' => function ($root) {
                return $root->linked_social_accounts;
            }
        ]
    ];
}

```

**Comment by tremby** [comment]
That does it; thank you. What I actually wanted was the other way around:

```php
'linked_social_accounts' => [
    'description' => "Social accounts linked with this user",
    'type' => Type::listOf(app('graphql')->type('LinkedSocialAccount')),
    'resolve' => function ($root) {
        return $root->linkedSocialAccounts;
    },
],
```
