### ISSUE TITLE
Pass graphql_schema parameter with graphiql

### ISSUE THREAD

**Issue by nwalke** [Folkloreatelier/laravel-graphql#115]
Is there a way to pass in the name of the schema I want via graphiql?  I've tried adding `graphql_schema=somethingnotdefault` to the URL, but it didn't do anything.

If I change the default schema to the new schema, it works just fine.  Just wondering if there's a better way than flipping that back and forth.

**Comment by dmongeau** [comment]
Yes, you can append it to the url:

```
/graphql/query/schema_name
```

You can have a look at the routes in the config, it's explained.

**Comment by nwalke** [comment]
I did look at the routes in the config, and I'm not sure how that helps for graphiql.

Looking at the routes config in the graphql config, I see this:
```
    // Same route for both query and mutation
    //
    // 'routes' => 'path/to/query/{graphql_schema?}',
    //
    // or define each routes
    //
    // 'routes' => [
    //     'query' => 'query/{graphql_schema?}',
    //     'mutation' => 'mutation/{graphql_schema?}',
    //     'mutation' => 'graphiql'
    // ]
    //
    // you can also disable routes by setting routes to null
    //
    // 'routes' => null,
    //
    'routes' => '{graphql_schema?}',
```

This is the graphiql config I have set:
```
    'graphiql' => [
        'routes' => '/graphiql',
        'middleware' => [],
        'view' => 'graphql::graphiql',
    ],
```

If I run `artisan route:list` I see this:
```
|        | GET|HEAD | graphiql                                | graphql.graphiql | Closure                                                                    |              |
|        | POST     | graphql/{graphql_schema?}               | graphql.mutation | App\GraphQL\GraphQLController@query                                        |              |
|        | GET|HEAD | graphql/{graphql_schema?}               | graphql.query    | App\GraphQL\GraphQLController@query                                        |              |
```

All of this to say, I don't know how to pass in `graphql_schema` or append it to the url...  The graphiql route doesn't seem to be set up to accept a schema name.  Am I missing something totally obvious here?

**Comment by ktogo** [comment]
@nwalke My PR #126 that solves this issue has been merged. Now you can specify the schema by the URL :)
