### ISSUE TITLE
Change Validation Error Message

### ISSUE THREAD

**Issue by wizston** [Folkloreatelier/laravel-graphql#117]
How do i change the default Laravel validation message to a custom one after setting rules on arguments.?

**Comment by nwalke** [comment]
It's just using Laravel's validation.  Custom message stuff can be found here: https://laravel.com/docs/5.4/validation#custom-error-messages

**Comment by mohammad-fouladgar** [comment]
You can override the getValidator method like this:
```
protected function getValidator($args, $rules)
{
    $messages = $this->getMessageValidation();

    return app('validator')->make($args, $rules, $messages);
}
```
then : 
```
protected function getMessageValidation()
{
    return [
        'input.email.required' => 'We need to know your e-mail address!',
    ];
}
```

**Comment by tafint** [comment]
@mohammad-fouladgar  i think change protected to public

**Comment by mohammad-fouladgar** [comment]
@tafint this feature merged into develop branch. Please review #266 or #261

**Comment by sadeghhosseini** [comment]
Why can't I just override the `validationErrorMessages` method?

**Comment by sadeghhosseini** [comment]
Overriding the `getValidator` method worked for me. 
```
    public $messages  = [
        'required' => 'shit has hit the fan',
        'email' => "gimme yo' EMAIL"
    ];
    protected function getValidator($args, $rules, $messages = [])
    {
        $validator = parent::getValidator($args, $rules, $messages);
        $validator->customMessages = $this->messages;

        return $validator;
    }
```
But I still can't understand the reason that the validationErrorMessages won't get called after I override it.
