### ISSUE TITLE
Route [graphql.query] not defined. In 1.0.14

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#121]
I have an error: "Route [graphql.query] not defined" in my middleware. I don't understand why it calls that middleware at all as it is for absolutely different routes.
Error occurs when i try to open graphiql page.

Using latest
Laravel 5.1

--
Rolled back graphql to 1.0.12 and it's fine now

**Comment by dmongeau** [comment]
Should be fixed in v1.0.15. Sorry about that, didn't know that Laravel cannot have to identical routes with different names so mutation route was overwriting the query routes which causes the error.
