### ISSUE TITLE
Unescaped unicode

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#122]
Can you add a config param to force unescape unicode in json responses?
It will economize bandwith for our multilingual app.

**Comment by dmongeau** [comment]
This is now possible in the version v1.0.16. You have a `json_encoding_options` parameter in the config.

**Comment by MCON** [comment]
If you set JSON_UNESCAPED_UNICODE 
you should also add response header:
`Contnt-Type: application/json; charset=UTF-8
`
Otherwise google chrome won't render non-utf characters in plain json properly.
