### ISSUE TITLE
How to implement analytics?

### ISSUE THREAD

**Issue by basith374** [Folkloreatelier/laravel-graphql#124]
I'd like to implement analytics. In my case keen.io. How do i do this? Basically i want to track queries and their params. Where do i add the code? Is there a controller for that or do i put this in Queries?

**Comment by n1ru4l** [comment]
@basith374 You will have to override the default controller:

https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/config/config.php#L44
https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQLController.php

**Comment by dmongeau** [comment]
You can do what @n1ru4l propose or create a middleware and add it to the config.
