### ISSUE TITLE
GraphiQL doesn't work in Lumen

### ISSUE THREAD

**Issue by dubcanada** [Folkloreatelier/laravel-graphql#128]
`View/GraphiQLComposer.php` uses `app('router')` this is not available in Lumen

You can fix it by doing something like

     try {
        $view->graphqlPath = app('router')->has('graphql.query') ? route('graphql.query') : url('/graphql');
      } catch (\Exception $e) {
        $view->graphqlPath = url('/graphql');
      }

But I am not sure what you want to do to fix this.

**Comment by dmongeau** [comment]
Should be fixed in v1.0.17

**Comment by arenowebdev** [comment]
@dmongeau This appears broken again in v1.0.18 for Lumen (probably works in Laravel). The route is bound if you do a `route('graphql.query')` check, but it appears Lumen doesn't bind anything to `app('router')` any more...

This is my `View/GraphiQLComposer.php` file that works as expected for Lumen 5.4.*:

    <?php 
    namespace Folklore\GraphQL\View; 
 
    use InvalidArgumentException; 
    use Illuminate\View\View; 
    use Illuminate\Support\Facades\Route; 
 
    class GraphiQLComposer 
    { 
        public function compose(View $view) 
        {   
            try { 
                $hasRoute = (bool) route('graphql.query'); 
            } catch (InvalidArgumentException $e) { 
                $hasRoute = false; 
            }              
                           
            $schema = $view->schema; 
            if (isset($schema) && !empty($schema)) { 
                $view->graphqlPath = $hasRoute ? route('graphql.query', [$schema]) : url('/graphql/'.$schema); 
            } else {       
                $view->graphqlPath = $hasRoute ? route('graphql.query') : url('/graphql'); 
            }              
        }                  
    }
