### ISSUE TITLE
Add example for mutations and for input (object) types

### ISSUE THREAD

**Issue by CapChrisCap** [Folkloreatelier/laravel-graphql#13]
I would be very pleased if you could add an example about how to create mutations with laravel-graphql as well as how to create input (object) types. 

Thanks :)

**Comment by chiedojohn** [comment]
Agreed!

**Comment by dmongeau** [comment]
Here it is https://github.com/Folkloreatelier/laravel-graphql#creating-a-mutation

**Comment by belohlavek** [comment]
How about custom input object types? I'm currently getting `Introspection must provide input type for arguments` when trying to use a defined Type as an argument!

**Comment by dmongeau** [comment]
For now, you can put an `$inputObject` property to true on your Type class and it will output an input type object. There will probably be a rework on this.

**Comment by Roemerb** [comment]
@dmongeau What's the status of this in 2018? 😄

**Comment by kisanme** [comment]
Experiencing the same problem as @belohlavek 's previous comment. 
Tagging @dmongeau

**Comment by indpurvesh** [comment]
I hope it helps. It took me ages to figure out too. so i hope it helps others.

Inside your Mutation File:


    /**
     * Expected arguments
     * 
     * @return array $arguments
     */
    public function args(): array
    {
        return [           
            'user' => [
                'name' => 'user', 
                'type' => Type::nonNull(new InputObjectType([
                    'name' => 'user',
                    'fields' => [
                        'first_name'=> ['name' => 'first_name', 'type' => Type::string()],
                        'last_name' => ['name' => 'last_name', 'type' => Type::string()],
                        'email'     => ['name' => 'email', 'type' => Type::string()],
                        
                    ]
                ]))
            ]
        ];
       }
