### ISSUE TITLE
Notation

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#133]
Hello! We are creating graphql api using your library.
Can you give a naming advice?
1. In your examples you always use singular word forms. 
Not Accessories but Accessory not car_models but car_model. Should we follow this?
2. Should i try to use snake case for root elements (not Accessory like below but accessory)

```
{
  Accessory {
    part_number
    name
    car_model {    <---- we have a list of models here
      name
    }
  }
}
```

P.S. We want to define some convention in our company to follow before it is too late.

**Comment by dmongeau** [comment]
I think if you have a list you should use a plural world. Also, not sure about the uppercase in Accessory. I mean your type should be named Accessory, but the query exposing it should be in lowercase in my opinion. You can view more info here: http://graphql.org/learn/schema/#type-system

**Comment by MCON** [comment]
>>but the query exposing it should be in lowercase in my opinion
How to achieve this? Can't figure out

**Comment by MCON** [comment]
{
  accessory {      <---- 1. How to use lower case here? 2. May be we should use plural here too?
    part_numbers
    name
    car_models {    
      name
    }
  }
}

**Comment by dmongeau** [comment]
When you define your query in the config:

```php

'query' => [
    'accessory' => \App\GraphQL\Query\AccessoryQuery::class,
]

```
