### ISSUE TITLE
Self-related type

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#136]
```
            'additional_accessories'     => [
                'type'        => Type::listOf(GraphQL::type('Accessory')),
                'description' => 'Список категорий к которым относится аксессуар',
                'resolve' => function ($root) {
                    return $root->additionalAccessories;  
                }
            ],
```

This accessories are self-related. Well i want to return related accessories id's only. Previosly they were stored in csv and turned into array in api controller.

To use grapqhl library i had to implement relations table etc. I feel like it is not as much efficient and i still want to hack somehow.

**Comment by dmongeau** [comment]
Not sure to totally understand, what is taking 2x+ longer? The queries? Have you tried eager loading your relation in the query?

**Comment by MCON** [comment]
Forgot to close this. I've exagerated
