### ISSUE TITLE
Return single field

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#138]
Hello!

I need to return a single field not really calling a model.
Not sure how to do it yet.

I need to return a checksum if you curious.

**Comment by malofan** [comment]
not sure, but i think you mean this:

--------------------------
namespace App\GraphQL\Type;
use App\GraphQL\Fields\checksumField;
class ModelType extends GraphQLType {
    public function fields()
    {
        return [
            'checksum' => checksumField::class,
        ]
    }
}

----------------------------

namespace App\GraphQL\Fields;

use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\Facades\GraphQL;
use Folklore\GraphQL\Support\Field;

class checksumField extends Field
{
    protected $attributes = [
        'description' => 'This is a checksum'
    ];

    protected function type()
    {
        return Type::string();
    }

    public function resolve($root, $args)
    {
        //resolve what you want right here
        // $root is you Model entity
    }
}

**Comment by n1ru4l** [comment]
You can also create a custom field
You can also create a field resolver method:

```php
protected function resolveEmailField($root, $args) {
  return strtolower($root->email);
}
```

(https://github.com/Folkloreatelier/laravel-graphql#creating-a-query)

**Comment by MCON** [comment]
Yes i've made it via resolve

`
    protected function resolveChecksumField($root, $args)
    {
        $query    = 'CHECKSUM TABLE accessories';
        $checksum = \DB::select(\DB::raw($query))[0]->Checksum;
        $query    = 'CHECKSUM TABLE accessories_additional_rel';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;
        $query = 'CHECKSUM TABLE accessories_car_complectations_rel';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;
        $query = 'CHECKSUM TABLE accessories_car_models_rel';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;
        $query = 'CHECKSUM TABLE accessories_category';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;
        $query = 'CHECKSUM TABLE accessories_category_rel';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;
        $query = 'CHECKSUM TABLE accessories_images';
        $checksum .= \DB::select(\DB::raw($query))[0]->Checksum;

        return hash('sha256', $checksum);
    }
`
