### ISSUE TITLE
WhereHas

### ISSUE THREAD

**Issue by MCON** [Folkloreatelier/laravel-graphql#139]
I need to get parent items only if they have specific nested items. Criteria should come with a query.

How to do that?

**Comment by MCON** [comment]
I've managed to do a query:

`{accessories(model_name:"Discovery"){id,name,car_models{name}}}
`

Is that the best way i can do?
May be it could be better to set condition inside car_models somehow? No?

**Comment by ttoohey** [comment]
You might look at https://github.com/ttoohey/laravel-graphql-filter

It allows filtering on relationships, so you can create a query builder expression like:

```
Accessory::filter( [ 'carModel' => [ 'name' => 'Camry'] ] )
```

and expose it as a graphql query argument like

```
{ accessories (filter: { carModel: { name: "Camry" } } ) { ... } }
```

**Comment by MCON** [comment]
Awesome!

**Comment by MCON** [comment]
Ah. Thats a separate library. I'm not sure if it is mature enaugh

**Comment by dmongeau** [comment]
Closing this!
