### ISSUE TITLE
relay cursors from query builder

### ISSUE THREAD

**Issue by ttoohey** [Folkloreatelier/laravel-graphql#147]
The offset and limit calculations in ResolvesFromQueryBuilder don't handle "after" in the expected way. Currently the cursor identified by "after" will be included in results when it shouldn't.

This is what I expect should happen:

```
(first: 10, after: null) --> { startCursor: "0", endCursor: "9" }
(first: 10, after: "9")  --> { startCursor: "10", endCursor: "19" }
(first: 10, after: "0")  --> { startCursor: "1", endCursor: "10" }
```

The "last" argument should use the count to identify where the last result is. For example, if count = 100:

```
(last: 10, before: null) --> { startCursor: "90", endCursor: "99" }
(last: 10, before: "90") --> { startCursor: "80", endCursor: "89" }
```

While it's not recommended, mixing "last" with "after" should first honour the "before" argument, but also ensure the result does not include the node at the "after" position.

```
(last: 10, after: "9")   --> { startCursor: "90", endCursor: "99" }
(last: 10, after: "95")  --> { startCursor: "96", endCursor: "99" }
(last: 10, after: "85", before: "90")  --> { startCursor: "86", endCursor: "89" }
(last: 10, after: "19", before: "50")  --> { startCursor: "40", endCursor: "49" }

```

Similarly for mixing "first" with "before". The "after" argument is honoured first, but the result does not include the node at the "before" position.

```
(first: 10, after: "19", before: "50") --> { startCursor: "20", endCursor: "29" }
(first: 10, after: "19", before: "25") --> { startCursor: "20", endCursor: "24" }
```

**Comment by dmongeau** [comment]
I've merged your pull request, thanks for this fix
