### ISSUE TITLE
cyclic relationships

### ISSUE THREAD

**Issue by lo3ty** [Folkloreatelier/laravel-graphql#15]
Hi there,

does anybody else have the problem that cyclic type relationships lead to an empty white page when quering?

e.g. in my case I have a comment type. one comment can have sub-comments and so on... unfortunately it is not possible to define these type relationship.

Example code:

    class CommentType extends GraphQLType {

        protected $attributes = [
            'name' => 'Comment',
            'description' => 'a comment to a wall entry'
        ];

        public function fields()
        {
            return [
                'id' => [
                    'type' => Type::nonNull(Type::int()),
                    'description' => 'The id of the comment'
                ],
                'text' => [
                    'type' => Type::nonNull(Type::string()),
                    'description' => 'the content of the comment'
                ],
                'author' => [
                    'type' => Type::nonNull(GraphQL::type("user")),
                    'description' => 'The id of the wall entry'
                ],
                'parent' => [
                    'type' => GraphQL::type("comment"),
                    'description' => 'parent comment'
                 ],
                 'comments' => [
                 'type' => Type::listOf(GraphQL::type("comment")),
                     'description' => 'comments on this comment'
                 ]
            ];
        }

        /**
         * @param Comment $model
         * @param array $args
         * @return Comment[] mixed
         */
        protected function resolveCommentsField($model, $args){
            return $model->children;
        } ...

in my comment model i defined the relation as follows:

        public function children(){
            return $this->hasMany(self::class,"fk_comment_id","id");
        }
  
as i mentioned before, quering this type does lead to an empty white page. I remove the cyclic relations (parent and comments) it works just fine.

Am I doing something wrong or is it an graph-ql implementation problem?

Leonhard

**Comment by dmongeau** [comment]
It's not supposed to cause any problem. But maybe one thing to do first, is try to have an error message of any kind. Do you have errors display enabled on your server?

Also, I'm curious what your GraphQL query looks like.

**Comment by dmongeau** [comment]
Okay, I think I see the problem. When the type is created, it needs itself to be created resulting in a recursive loop. Since GraphQL needs an instance of an object type to consider it as the same type, I don't really see how you can do it besides creating Comment, ChildComment, etc...

Anyway since you cannot use wilcard on GraphQL query, I don't see how you could query an infinite level of children.

**Comment by lo3ty** [comment]
sadly, this makes totally sense. 
thanks for pointing this out.

**Comment by bcarroll22** [comment]
I think this needs to be resolved somehow. Being able to do this sort of thing is fundamental to GraphQL. I see that they resolved this issue in the webonyx package already. What could be done to enable this here? I'd be willing to help with the effort to get it done.
