### ISSUE TITLE
Merging schema instead of replacing in GraphQL::addShema()

### ISSUE THREAD

**Issue by Phirames** [Folkloreatelier/laravel-graphql#151]
First, I want  to thank you for your amazing work! 

My problem is that I can't add schema in multiple places in my code. I use module app architecture (using this [package](https://github.com/nWidart/laravel-modules) ) where every module has its own service provider. When I use GraphQL::addShema('default', $schema) in my modules service providers the schema is replaced by the last invocation in module service provider which was invoked last.
What I want is GraphQL to have a method which merges schema instead of replace it. 

Here is my workaround for those who faced this problem as well
I created my own GraphQL service provider and registered my own GraphQL singleton which has desired mergeSchemas method
```php
namespace App\GraphQL;

use Folklore\GraphQL\Events\SchemaAdded;

class GraphQL extends \Folklore\GraphQL\GraphQL
{
    public function addSchema($name, $schema)
    {
        $this->mergeSchemas($name, $schema);

        event(new SchemaAdded($schema, $name));
    }

    private function mergeSchemas($name, $schema) {

        if (isset($this->schemas[$name]) && $this->schemas[$name]) {

            $this->schemas[$name] = array_merge_recursive($this->schemas[$name], $schema);
        } else {

            $this->schemas[$name] = $schema;
        }
    }
}
```

**Comment by dmongeau** [comment]
Hello,
Maybe it's just a matter of putting the GraphQL ServiceProvider before in you config/app.php ?

Cheers

**Comment by MrGekko** [comment]
I am having the same issue. How do you propose I do this. I would like to compose one schema out of multiple packages.
