### ISSUE TITLE
Please allow OPTIONS request

### ISSUE THREAD

**Issue by LLoyou00** [Folkloreatelier/laravel-graphql#157]
When 'fetch' function of JS be use to initiate a cross domain request by front end, an OPTIONS request will be send to server to detect whether the server allow cross domain request or not. 
But the '/graphql' allow GET and POST method only, so that the fetch function can not continue.

My stupid solution is add the follow  code to 'index.php'
```php
if ('OPTIONS' == $_SERVER['REQUEST_METHOD']) {
    exit();
}
````

**Comment by dmongeau** [comment]
I don't think it should be part of this package. You can use https://github.com/barryvdh/laravel-cors to solve your problem

**Comment by LLoyou00** [comment]
You are right,thanks.

At 2017-08-17 23:22:57, "David Mongeau-Petitpas" <notifications@github.com> wrote:


I don't think it should be part of this package. You can use https://github.com/barryvdh/laravel-cors to solve your problem
