### ISSUE TITLE
Eager Loading Constraints w/ Arguments

### ISSUE THREAD

**Issue by chrissm79** [Folkloreatelier/laravel-graphql#16]
Is there currently a way to get the arguments of a relationship in the resolve function? With the following (using the instructions in the README) I can determine if I need to eager load a relationship in the **parent's** resolve:

```php
class CustomersQuery extends Query
{
    //...
    public function resolve($root, $args, ResolveInfo $info)
    {
        $customers = Customer::query();
        $fields = $info->getFieldSelection(3);

        foreach ($fields as $field => $keys) {
            if ($field == 'orders') {
                // Can I get the arguments for orders here so I can put 
                // a constraint on the relationship? For Example:
                // $customers->with(['orders' => function ($q) use ($args) {
                //     $q->take($args['orders.limit']);
                // }]);
                $customers->with('orders');
            }
        }

        return $customers->take($args['limit'])->get();
    }
}
```

And with my type definition I can add arguments and grab them in the **field's** resolve function:

```php
class CustomerType extends GraphQLType
{
    public function fields()
    {
        $orderType = new OrderType;

        return [
            // ...
            'orders' => [
                'type' => Type::listOf($orderType->toType()),
                'description' => 'Customer orders.',
                'args' => [
                    'limit' => [
                        'name' => 'limit',
                        'type' => Type::nonNull(Type::int())
                    ]
                ],
                'resolve' => function ($customer, $args) {
                    return $customer->orders()->take($args['limit'])->get();
                }
            ]
        ];
    }
}
```

However, at that point I've already pull all related records from the DB. Is there a way to get the arguments in the parent's resolve function?

Btw, this package has made working with GraphQL an absolute joy!

**Comment by dmongeau** [comment]
You could probably be able to retrieve that by using `$info->fieldASTs`, and maybe `$info->fieldASTs->selectionSet`. Try to var_dump, I think it contains the arguments.

Also, I just want to point out that you are using the type in the wrong way for OrderType. You should define the `order` type in the `config/graphql.php` and then use it this way `Type::listOf(GraphQL::type('order'))`. `GraphQL` being the facade and `'order'` being the name you put in the `config/graphql.php`. This way ensure that every object definition will use the same instance of the `ObjectType` which will prevent a GraphQL error saying that there is a duplicate object `'Order'`. The way you are doing will work until you use the OrderType somewhere else.

**Comment by chrissm79** [comment]
JUST ran into the issue of duplicate orders, so thanks for pointing that out!!

I am stumbling my way through fieldASTs and I'll get what I need out of it (I can see the arguments nested in there). Thanks for pointing me in the right direction, I'll see what kind of solution I can come up with!

**Comment by joshhornby** [comment]
@chrissm79 What solution did you come up with in the end?

**Comment by chrissm79** [comment]
I haven't come up with a solid solution for this one yet, but when I do I'll likely submit a PR.
