### ISSUE TITLE
Instantiating all the queries definded in requested schema.

### ISSUE THREAD

**Issue by satyaprakashcedcoss** [Folkloreatelier/laravel-graphql#169]
If there is request of one query for getting only User Name then it is instantiating all the queries definded in graphql config.

E.g:
```
'schemas' => [
    'default' => [
        'query' => [
            'User' => 'Module\Base\User\Query',
            'AclRole'=>'Module\Base\AclRole\Query',
            'Admin'=>'Module\Base\Admin\Query',
            'AdminRole'=>'Module\Base\AdminRole\Query',
            .
            .
            .
        ],
        'mutation' => [
        ]
     ]
],
```
And now if requesting User Name and Email
Then its instantiating all queries User,AclRole,Admin,AdminRole etc.

Is there any way to instantiate only requested Queries ?

**Comment by dmongeau** [comment]
Not really at the moment since graphql needs to know the full schema (all your queries and types)
