### ISSUE TITLE
Returning more than one type

### ISSUE THREAD

**Issue by Simplesmente** [Folkloreatelier/laravel-graphql#170]
I did my class PostQuery like this:

```
class PostQuery extends Query
{
    protected $attributes = [
        'name' => 'Post',
        'description' => 'A query Post'
    ];

    public function type()
    {
        return GraphQL::type('Post');
    }

    public function args()
    {
        return [
            'id' => ['name' => 'id', 'type' => Type::int()]
        ];
    }

    public function resolve($root, $args, $context, ResolveInfo $info)
    {
          if( isset($args['id'])){
              return Post::find($args['id']);
          }
              return Post::all();


    }
}
```

But in method type() I must return only one type. My question is:

I would like return a type GraphQL::type('Post') when I'm quering by only one Post:

```
query {
	posts(id: 5 ){
        id
        title
  }
}
```

 And a Type::listOf(GraphQL::type('Post')) when I'm quering for many Posts.

```
query {
	posts{
    id
    title
  }
}
```
 How to do this in my class?

I thougth some thing like this:

```
public function type()
{
        return GraphQL::type('Post') || Type::listOf(GraphQL::type('Post'));

 }
```

 But I tried and it don't works.

Someone can help me about this question?

**Comment by n1ru4l** [comment]
This is not part of the graphql spec. Therefore you should create separate endpoints for lists of posts and a single post.

**Comment by SonarSoftware** [comment]
I would also add that it is not really a very good practice to follow. For example, imagine you later add the ability to filter by author as well as ID, and author can sometimes return 1 post, or 10. It will be tedious for the consuming party to always check if the result is an array or not.

**Comment by vladar** [comment]
Just define it as a list and return one or many. It will be also more convenient for clients to process such response vs analyzing if it is object or list.

**Comment by Simplesmente** [comment]
Thanks for attention.
