### ISSUE TITLE
Parse Graphql args in middleware

### ISSUE THREAD

**Issue by drmax24** [Folkloreatelier/laravel-graphql#177]
I need to do some preprocessing for the graphql Query in middleware. Can i parse incoming graphql via this package somehow?

**Comment by mikeerickson** [comment]
What kind of parsing are you referring to?  Are you talking about parsing results after your query request? Or are you needing to do something before the request is sent

**Comment by drmax24** [comment]
query request.
I need to run smth before it goes after middleware

**Comment by mikeerickson** [comment]
You have full access to request object in middleware and can modify as you wish before passing it along. What does your middleware do?  

Perhaps you can share your middleware for more clarification.

**Comment by drmax24** [comment]
>>You have full access to request object
Yes but i have a graphql query as a string. Can i parse it?

**Comment by mikeerickson** [comment]
I am sure you can do what you want.  Perhaps you can share some sample code?  More than willing to help, just trying to understand

**Comment by drmax24** [comment]
Here is a sketch
```
    public function handle($request, Closure $next, $guard = null)
    {
        $sessionToken = preg_match('~sessionToken:~',$request->getQueryString());
        $user = User::first();
        \Registry::add($user, 'currentUser');
        return $next($request);
    }
```

**Comment by SonarSoftware** [comment]
This feels like the wrong way to approach this - is there a reason you have to do it in the middleware rather than using the resolve function of the query, or the resolve option on the types?

**Comment by dmongeau** [comment]
I agree with SonarSoftware, you should use the resolve method since you want to play with the query itself and in a middleware it is not parsed yet.
