### ISSUE TITLE
Add methods which run before and after validations

### ISSUE THREAD

**Issue by tremby** [Folkloreatelier/laravel-graphql#181]
I would find it useful to have a method, no-op by default, which I can override in mutations and queries to run tests based on the request and throw an exception if the query/mutation shouldn't proceed *before* validations have run.

One example use case is a mutation which requires a higher level of authentication than others. I don't even want the validations to run if the user making the request doesn't have the necessary permission, so in this case I want the "unauthorized" error to be higher priority than any validation issue which may have occurred.

It may also be useful to have a method which runs after validations but before resolve. I can imagine situations in which this would reduce boilerplate where a lot of query inheritance is employed.

So I imagine the lifecycle as something like...

1. Request comes in, any pre middlewares run
2. The query/mutation's `preValidation` runs, and either returns or throws an exception. If an exception is thrown, an error is returned for that query/mutation.
3. Any validation the query/mutation calls for occurs. If it fails, the errors are returned for this query/mutation (this is current behaviour)
4. The query/mutation's `postValidation` runs, and either returns or throws an exception. If an exception is thrown, an error is returned for that query/mutation.
5. The `resolve` method runs (current behaviour).

Where I want something to run before the validators, I currently hack it into `getResolver`, as I showed in https://github.com/Folkloreatelier/laravel-graphql/issues/156#issuecomment-323158559.

**Comment by tremby** [comment]
My current workaround is to have a trait which reimplements `getResolver` of the `shouldValidate` trait:

```php
<?php

namespace App\GraphQL;

trait PrePostValidationTrait
{
    protected function getResolver()
    {
        $resolver = parent::getResolver();
        if (!$resolver) {
            return null;
        }

        return function () use ($resolver) {
            $arguments = func_get_args();

            if (method_exists($this, 'preValidation')) {
                call_user_func_array([$this, 'preValidation'], $arguments);
            }

            if (method_exists($this, 'getValidator')) {
                $rules = call_user_func_array([$this, 'getRules'], $arguments);
                if (sizeof($rules)) {
                    $args = array_get($arguments, 1, []);
                    $validator = $this->getValidator($args, $rules);
                    if ($validator->fails()) {
                        throw with(new ValidationError('validation'))->setValidator($validator);
                    }
                }
            }

            if (method_exists($this, 'postValidation')) {
                call_user_func_array([$this, 'postValidation'], $arguments);
            }

            return call_user_func_array($resolver, $arguments);
        };
    }
}
```

I then have base classes `Query`, `ValidatingQuery` and `Mutation`.

`Query` is just an abstract extension of the provided `Query` class which adds nothing new.

`Mutation` is an abstract extension of the provided `Field` class (extending `Mutation` would pull in `shouldValidate`, which conflicts with my trait) which imports the traits as required:

```php
<?php

namespace App\GraphQL\Mutation;

use App\GraphQL\PrePostValidationTrait;
use Folklore\GraphQL\Support\Field;
use Folklore\GraphQL\Support\Traits\ShouldValidate;

abstract class Mutation extends Field
{
    use PrePostValidationTrait, ShouldValidate {
        PrePostValidationTrait::getResolver insteadof ShouldValidate;
    }
}
```

`ValidatingQuery` is actually almost identical to `Mutation` but extends from my `Query` class:

```php
<?php

namespace App\GraphQL\Query;

use App\GraphQL\PrePostValidationTrait;
use Folklore\GraphQL\Support\Traits\ShouldValidate;

abstract class ValidatingQuery extends Query
{
    use PrePostValidationTrait, ShouldValidate {
        PrePostValidationTrait::getResolver insteadof ShouldValidate;
    }
}
```

Then I extend these for my queries as appropriate, and define `preValidation` or `postValidation` as required. So far I've done this with other traits, for example

```php
<?php

namespace App\GraphQL;

use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

trait Auth
{
    protected function preValidation()
    {
        // Ensure user is logged in, not disabled, and an influencer
        $user = app('auth')->user();
        if (!$user || !$user->enabled) {
            throw new UnauthorizedHttpException('auth', 'unauthorized');
        }
    }
}
```

And then used as such:

```php
<?php

namespace App\GraphQL\Mutation;

use App\GraphQL\Auth;
use GraphQL\Type\Definition\Type;

class UpdateUserPasswordMutation extends Mutation
{
    use Auth;

    protected $attributes = [
        'description' => "Update user's password",
...
```

Things I don't like about this:

- It's messy
- I no longer override the base `Mutation` class, which might not be future-proof
- I rely on the base implementation of `shouldValidate` not changing (I have to notice and take action when it does), which is not future-proof

**Comment by niiapa** [comment]
@tremby I moved to rebing's library. It's build ontop of this one and it has extra functionality like authorize which you can use to check for authorization prior to mutations or queries...

**Comment by tremby** [comment]
Looks like you mean [this package](https://github.com/rebing/graphql-laravel). I'll look into it.

**Comment by niiapa** [comment]
Yup. Have fun. If you need help, holla

**Comment by dmongeau** [comment]
There is an `authorize` method that you can override in any queries, mutations or fields which does what you want.

**Comment by niiapa** [comment]
@dmongeau Wait did you add authorization to this package?! Because if yes, thank you!

**Comment by dmongeau** [comment]
Yes, added from a PR. I'm working on releasing the feature/relay branch into 1.1 (branch v1.1) and I've moved authorization to a trait like validation.

**Comment by tremby** [comment]
Thanks, but validators still run before the `authorize` method, so this doesn't do what I was asking for. Please reopen.

**Comment by tremby** [comment]
Example use case: a change password mutation.

Authorization is required: a valid user needs to be logged in.

Validation is required: the new password needs to match some criteria (minimum length), and the old password must be correctly given as an extra security measure.

The old password validator's logic depends on there being a user logged in. It doesn't make sense to run it when no user is logged in. In my implementation, this validator will throw an exception in this case.

If there is no user logged in it could conceivably still be useful to return a validation error if the new password doesn't match the criteria, but we have no data at all about whether the old password matches, since there's no user. But the important thing is that the user is unauthorized, so this should certainly be in the error message.

However, ignoring for now the old password validator, the error message given back to the user talks only about the new password (if this fails validation), and the `authorize` method hasn't even run.

This should be the other way around. If the `authorize` method return false, the error should be returned immediately. Validators should only run if `authorize` returned true.
