### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by kevinvdburgt** [Folkloreatelier/laravel-graphql#187]
How can I use pagination in resources (Laravel Models) so the client knows how many 'pages' there are?

**Comment by SonarSoftware** [comment]
You would have to implement something yourself, there is nothing in the library specifically to deal with this. Check out http://graphql.org/learn/pagination/ for some ideas.

**Comment by kevinvdburgt** [comment]
I have seen that page, but I am still unsure how I should apply this in Laravel. For example, I have a query with the type:

```
public function type()
{
    return Type::listOf(GraphQL::type('User'));
}
```

I still want to return a list of the type User but I want to wrap that listOf in a separate container so I can add pagination info. Is there a special type for it?

**Comment by dmongeau** [comment]
You should create another type with the pagination. Something like this:

```php
public function type()
{
    return GraphQL::type('UsersWithPagination');
}
```

```php

class UsersWithPagination extends Type
{
    public function fields()
    {
        return [
            'pagination' => [
                'type' => GraphQL::type('Pagination')
            ],
            'items' => [
                'type' => Type::listOf(GraphQL::type('User'))
            ]
        ]
    }
}
```
