### ISSUE TITLE
Enum as an Input field

### ISSUE THREAD

**Issue by avirdz** [Folkloreatelier/laravel-graphql#188]
I'm trying to use an Enum type in an Input field but I'm getting the following error,

```
'account_type' => [
    'description' => 'Account type',
    'type' => GraphQL::type('AccountType'),
],
```

`
Type error: Argument 2 passed to GraphQL\Executor\Values::isValidPHPValue() must implement interface GraphQL\Type\Definition\InputType, instance of GraphQL\Type\Definition\ObjectType given, called in /app/vendor/webonyx/graphql-php/src/Executor/Values.php on line 191
`

These docs say you can use Enum on Input Types.
http://webonyx.github.io/graphql-php/type-system/input-types/

Is there a way to use Enum in Input types?

**Comment by avirdz** [comment]
This was working before I update Laravel to 5.5, now I cannot install the last release of this repo because the dependency list doesn't have Laravel 5.5. :(

I saw that the develop branch already has the support for 5.5.
When do you guys will program another release?

**Comment by dmongeau** [comment]
I've added 5.5 support

**Comment by avirdz** [comment]
thanks a lot :D
