### ISSUE TITLE
Eager Loading & iterable error

### ISSUE THREAD

**Issue by joshhornby** [Folkloreatelier/laravel-graphql#19]
[I have followed the Readme for eager loading] (https://github.com/Folkloreatelier/laravel-graphql#eager-loading-relationships)

```
public function resolve($root, $args, ResolveInfo $info)
{
    $fields = $info->getFieldSelection($depth = 3);

    $users = User::query();

    foreach ($fields as $field => $keys) {
        if ($field === 'team') {
            $users->with('team');
        }
    }

    return $users->get();
}
```

This query runs successfully in my app.
```
[2015-11-12 11:22:46] View Logs.INFO: select * from `teams` where `teams`.`id` in (?, ?, ?) [1,2,3] []
```

And in my `UserType` class I have the following in the `fields` function 

```
'team' => [
    'type' => Type::listOf(GraphQL::type('team')),
    'description' => 'The users team',
]
```
I am getting the following error: 

```
User Error: expected iterable, but did not find one.
```

If I add a `resolve` function to the team array it works but I then loose the eager loading functionality:

```
'team' => [
    'type' => Type::listOf(GraphQL::type('team')),
    'description' => 'The users team',
    'resolve' => function($data, $args) {
         return $data->team()->get();
    }
]

**Comment by chrissm79** [comment]
What's your User/Me Type and Query look like?

**Comment by joshhornby** [comment]
**User Type**

```
class UserType extends GraphQLType
{
    /**
     * @var array
     */
    protected $attributes = [
        'name' => 'User',
        'description' => 'A user',
    ];

    /**
     * @return array
     */
    public function fields()
    {
        return [
            'uuid' => [
                'type' => Type::nonNull(Type::string()),
                'description' => 'The uuid of the user'
            ],
            'email' => [
                'type' => Type::nonNull(Type::string()),
                'description' => 'The email of user'
            ],
            'team' => [
                'type' => Type::listOf(GraphQL::type('team')),
                'description' => 'The users team',
            ]
        ];
    }
}

```
**Team Type**
```
class TeamType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Team',
        'description' => 'A team',
    ];

    public function fields()
    {
        return [
            'name' => [
                'type' => Type::nonNull(Type::string()),
                'description' => 'The name of user'
            ]
        ];
    }
}
```

**Query**
```
query=query+FetchUsers{users{uuid, email, team{name}}}
```

**Comment by chrissm79** [comment]
It looks like the query you supplied is requesting a "UsersQuery". That would tell me that it's likely (Would need to see that query class) returning a Type::listOf(GraphQL::type('user')). What the message is saying is that it's expecting a **list** of User rather than just one user. Can you post your UsersQuery class?

**Comment by joshhornby** [comment]
Sure, see below.

**UserQuery**

```
class UserQuery extends Query
{

    protected $attributes = [
        'name' => 'Users query'
    ];


    public function type()
    {
        return Type::listOf(GraphQL::type('user'));
    }


    public function args()
    {
        return [
            'uuid' => ['name' => 'uuid', 'type' => Type::string()],
        ];
    }


    public function resolve($root, $args, ResolveInfo $info)
    {
        $fields = $info->getFieldSelection($depth = 3);

        $users = User::query();

        foreach ($fields as $field => $keys) {
            if ($field === 'team') {
                $users->with('team');
            }
        }

        if(isset($args['uuid'])) {
            User::where('uuid', $args['uuid'])->get()
        }

        return $users->get();
    }
}
```

**Comment by chrissm79** [comment]
This looks correct, $users->get() should return a Collection as well as $data->team()->get() (in the team resolve function in your first post). If you want you can email me and we can dig around a bit more. These queries have been working pretty well for me so far.

**Comment by joshhornby** [comment]
I can get it to work with `$data->team()->get()` but I then get a stream of queries and end up with an `n+1` issue. I will try and get an example repo online if this would help?

**Comment by joshhornby** [comment]
@chrissm79 Have you got an example of the queries that you have been using?

**Comment by dmongeau** [comment]
What if you do:

```php
dd($users->get());
```

Just to be sure the results is what you expect. Then I will suggest that you wrap the return in a try catch and inspect the Exception.

```php
try {
    return $users->get();
}
catch(\Exception $e)
{
    dd($e);
}
```

In my experience so far, GraphQL can be hard to debug since it catches any error, this is how I find problems for now.

**Comment by joshhornby** [comment]
If I `dd` my users I get a `Collection` which includes 

```
 #relations: array:1 [
        "team" => Team {#535
```

**Comment by dmongeau** [comment]
Ok so the team relation is not a collection, you should remove the Type::listOf in your team field and only use GraphQL::type('team'). Should work.

**Comment by joshhornby** [comment]
That seems to have fixed it! Brilliant. Thanks @dmongeau :+1:
