### ISSUE TITLE
Diffrent types per schema (Field permissions user/admin)

### ISSUE THREAD

**Issue by kevinvdburgt** [Folkloreatelier/laravel-graphql#198]
What is the best way of serving different representations of the GraphQL Types?

For example, I have a ChatMessageType with the fields: `id`, `to_user_id`, `from_user_id`, `message` and `flagged_as_spam`. The admin has to be able to see all the fields, the user should see all the fields except for the `flagged_as_spam` field.

I was thinking about about the following solutions:
1. Create a custom type `UserChatMessageType` with all the fields except the `flagged_as_spam` field.
2. Use the `ChatMessageType` but leave the `flagged_as_spam` empty (null). However, there are some types where a lot will be set to null for the user when using this solution, which will bloat the generated docs.

What is the best approach to achieve this?

**Comment by n1ru4l** [comment]
You could use different schemas by overwriting the controller

**Comment by kevinvdburgt** [comment]
Yes, i have multiple schema's but the types are not in the schemas, only the queries and mutations.

**Comment by n1ru4l** [comment]
Ok you could either use one of your suggested solutions. I think 1. would be the better approach if you do not want to expose internal type field names to your consumers.

Or we could implement some methods like `isFlaggedAsSpamFieldVisible` (similar to the `resolveIsFlaggesAsSpamField` methods), that gets passed in the context from which you could return a boolean (or promise/deferred that resolves to a boolean).

@dmongeau Would you accept a PR for this?

**Comment by kevinvdburgt** [comment]
I've found that you can create types specific for schema's here: https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQL.php#L55-L61

However, I am not really sure how this should work, when adding types, it is there in the schema file, however, when using that type in the same schema I got the TypeNotFound exception.
https://gist.github.com/kevinvdburgt/cc00d59ab12ee3f2233e6f87d9d351d5

**Comment by kevinvdburgt** [comment]
@n1ru4l could you please take a look at this issue?

**Comment by kevinvdburgt** [comment]
@dmongeau could you please take a look at this issue?

**Comment by leehicks** [comment]
I am trying to define "types" in various schemas as well and found that the TypeNotFound is a bug coming from [line 91](https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQL.php#L91). If you comment that out you will see that the type is picked up correctly in the following lines of "typesInstances" in my case, and the queries continue to work.

**Comment by kevinvdburgt** [comment]
I see, I've got it working as well, by adding `$this->addTypes($types);` at [line 67](https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQL.php#L67).

And the using this config:
```php
'schemas' => [
    'default' => [
        'query' => [
            'TestQuery' => \App\GraphQL\Query\TestQuery::class,
        ],
        'mutation' => [

        ],
        'types' => [
            'TestType' => \App\GraphQL\Type\TestType::class,
        ],
    ]
],
```

However, I am not sure if this will give any issues with this library. (Havent found any yet).

@dmongeau Do you think it is safe to accept a PR for this?
