### ISSUE TITLE
Where's the config file?

### ISSUE THREAD

**Issue by kiddyatreides** [Folkloreatelier/laravel-graphql#204]
I wanna ask, should I always open the vendor/folkloreatelier/config/config.php to config anything? Why after I do a publish it doesn't come to my config folder?

**Comment by thomassjogren** [comment]
I couldn't get the automatic discovery to work with Laravel 5.5.9. Refuse to find the package so I had to register the service provider manually in order for the `php artisan vendor:publish` command to work.

**Comment by kiddyatreides** [comment]
Well I am using Laravel 5.4.30 so i should register the service provider manually?

**Comment by thomassjogren** [comment]
That is correct.

https://github.com/Folkloreatelier/laravel-graphql#laravel--54x

**Comment by kiddyatreides** [comment]
Well I already add it into my config -> app.php to provider section, when I try to `php artisan vendor:publish` it doesn't change anything and the graphql.php don't come into my config folder

**Comment by kiddyatreides** [comment]
well now its work! I just do `php artisan vendor:publish` without the `php artisan vendor:publish --provider="Folklore\GraphQL\ServiceProvider"` and its work :dancing_men:
