### ISSUE TITLE
GraphQL Artisan commands

### ISSUE THREAD

**Issue by StefanJanssen95** [Folkloreatelier/laravel-graphql#211]
EDIT: As it turns out there are some artisan commands already. I will expand on this instead of remaking them like described below.

I'm currently working on a Laravel project with GraphQL included. Because there are no artisan GraphQL class file generators at the moment I'm adding those into the project I'm working on.
Currently I'm finishing up these commands and would like to know if people would like it if I make a pull request to add them in the package. 

Currently I've implemented commands for Types (``graphql:type <name>``) and Queries (``graphql:query <name>``) and I'm working on the implementation of mutations.

I would like to get your opinion about this. Any ideas are welcome.

Todo list:
- [x] Enums
- [x] Mutations
- [x] Scalars
- [X] Types
- [X] Queries

**Comment by SonarSoftware** [comment]
I think it's a nice idea, I have already done the same thing internally for my own project, but it is definitely a good addition.

I'd suggest one for scalars and enums as well, if you're working through them!

**Comment by StefanJanssen95** [comment]
Thanks, I know about GraphQL for a week or two now. I will add these things to my todo list.

**Comment by kevinvdburgt** [comment]
Doesn't `php artisan make:graphql:type <name>` and `php artisan make:graphql:mutation <name>` already exists?

**Comment by StefanJanssen95** [comment]
@kevinvdburgt It doesn't show them for me in the list of artisan commands when I use ``php artisan list``. So unless they are hacked in there I'm pretty sure they aren't

**Comment by kevinvdburgt** [comment]
Hmm, I can see them when typing `php artisan` between the other make commands.

See; https://github.com/Folkloreatelier/laravel-graphql/tree/master/src/Folklore/GraphQL/Console

**Comment by StefanJanssen95** [comment]
Hmm I will check tomorrow why I don't see them and I will add generators for the other classtypes as well.

**Comment by kevinvdburgt** [comment]
It might be that you have an older version of the library :)

**Comment by StefanJanssen95** [comment]
Hmmm I started using it this week and used the master branch when including it in my project. But I will check tomorrow to be sure.

**Comment by kevinvdburgt** [comment]
Hmm, that should not be the problem then. Those console commands are over a year old.

But having more console commands to create those clases (enums, scalars etc..) would be awesome!
