### ISSUE TITLE
license for this project

### ISSUE THREAD

**Issue by itsnothingg** [Folkloreatelier/laravel-graphql#233]
thank you for your great project.
your project helped me a lot in getting to GraphQL.
easy to use, codes are clear, good docs.
so I was about to publish a commercial app using this lib.
but before, may I know what license this project follows?
does it follow no-license as posted here? 
https://choosealicense.com/no-license/
I want to make sure if I may use this project in commercial purpose.

thanks.

**Comment by dmongeau** [comment]
MIT Licence (it's in the composer.json file) so yes, feel free to use it
