### ISSUE TITLE
Lumen : Args in controller of route must have the same names of query parameters

### ISSUE THREAD

**Issue by mickaelvalmier** [Folkloreatelier/laravel-graphql#249]
Hi @dmongeau ,

My PR #241 was to fix a problem about routing in Lumen but you have rollbacked changes with commit https://github.com/Folkloreatelier/laravel-graphql/commit/6c25a5777220f98b781e80b1210414dc8abfb550 .

Args in controller MUST have the same names of query parameter : 
<img width="679" alt="capture d ecran 2017-12-17 a 16 33 19" src="https://user-images.githubusercontent.com/13783395/34081069-1fa80c08-e348-11e7-81aa-3030d8d76ef2.png">

It's possible to apply my changes ?

Thx

**Comment by dmongeau** [comment]
Sorry about that, it is fixed in v1.0.35
