### ISSUE TITLE
Rules on custom fields

### ISSUE THREAD

**Issue by chrissm79** [Folkloreatelier/laravel-graphql#27]
This is more of an suggestion, but I have a custom field that requires arguments and I'd like to use the built-in validation. It only took me a few minutes to realize that a Mutation is nothing more than of Field that has rules applied. I simply switched my Field to extend a Mutation instead and everything works fine, but I'm wondering if that logic could be placed in the Field and still have the Mutation type extend it just for naming purposes. 

Alternatively, maybe the logic could be put into a trait which mutations use and the user can choose to add the trait to have validation run on a custom field's arguments (something like ShouldBeValidated). 

Thanks!

**Comment by dmongeau** [comment]
I've implemented your suggestion (validation as a trait) in 1.0.0. Thanks!
