### ISSUE TITLE
Add support for caching

### ISSUE THREAD

**Issue by pSchaub** [Folkloreatelier/laravel-graphql#302]
Please add support for caching. With large database structures this GraphQL library will get very slow. 

A manual caching inside the `resolve()` function is not working because the GraphQL library will still go through the complete structure and will still be slow.

The library itself needs support for caching to prevent it's own slowness on big structures.

**Comment by kevinvdburgt** [comment]
I have quite a large MySQL database, but dont experience any issues you have. How do you resolve your data?

**Comment by pSchaub** [comment]
@kevinvdburgt We have a lot of nested stuff. We fetch the data from a redis cache so the data receiving is not the slow part. I think the slowness comes from the filtering of this GraphQL library.

```
{
  pages {
    id,
    title,
    route,
    authType,
    grid

    pagecomponents {
      id

      component {
        id,
        name,
        tag

        componentattributes {
          id,
          name,
          default_value,
          tag,
          type

          componentattributetranslations {
            id,
            value
            language {
              name,
              iso_code
            }
          }
        }
      }

      pagecomponentattributes {
        id,
        value

        componentattribute {
          id,
          name,
          default_value,
          tag,
          type
        }

        pagecomponentattributetranslations {
          id,
          value
            language {
            name,
            iso_code
          }
        }
      }
    }
  }
}
```

**Comment by kevinvdburgt** [comment]
I see, do you have any profiling tools like BlackFire so you can see if it is because of the library?

**Comment by pSchaub** [comment]
We checked it with Blackfire. The data is still coming from the database through Eloquent even if we use a manual cache. The GraphQL library is fetching the nested stuff for us even if we already have the data thanks to a cache (e.g. redis cache)

Is there a way to disable the automatic Eloquent fetching and just return the result that we stored in the cache?

**Comment by kikoseijo** [comment]
@pSchaub you mean that you have large data structures and this library goes trough the structure to fetch the data?
I thought this library does not fetch data only resolves the queries to the right resolve function.

Could it be you don't have well configured the cache? What you have above looks good to me, 60 secs could not be enough, im more into permanent cache way and refresh it when data change. But at the same time I save cache on database, so a query to it its needed.

Interesting topic.---

**Comment by pSchaub** [comment]
I found the reason why the cache was not working in my code. I will explain here what we thought and how we solved it.

We also thought that this GraphQL library is doing own Eloquent queries "on the fly" itself.
I am not sure how it really technically works but I think my assumption was only partially correct. 
I think this library is only working on the properties of the objects that I return in `resolve()`. Then this library may call the properties that I specified in my `Type` and triggers a database query because Eloquent is fetching the data "on the fly" once you try to access a property. This is how I understand it - i am not sure if this information is correct. Maybe somebody could explain better what really is happening in combination with Eloquent Models.

The described magic property calls can be very funny if you are using relationships. For example if a `User` has `comments`. You need to be really careful how you name the relationships in your `Type` if you use a cache implementation - otherwise you may fall into the same bug.

I will show you want we do in our project and how I fixed the weird cache bug in my case.

In our case we have a `Page` and according `PageComponent`s.
```
 public function resolve($root, $args, $context, ResolveInfo $info)
    {
        return Cache::remember('pages', 60, function() {
            return Page::with(['PageComponents'])->get();
        });
    }
```

Query:
```
{
  pages {
    id,
    title
    pagecomponents {
      id
    }
}
```

Fields in `PageType`:
```

    public function fields()
    {
        return [
            'pagecomponents' => [
                'type' => Type::listOf(GraphQL::type('PageComponent')),
                'description' => 'The page components of the page'
            ],
        ];
    }
```

I am not sure if every developer will instantly see the issue behind this. The issue is simple: Once the cache is building the first time from the database the structure will be `page` -> `page_components`. But over the GraphQL type we described the structure as `page` -> `pagecomponents`.

So this small difference will lead into not using the cache for `pagecomponents` but instead running a fresh database query each time this GraphQL library is accessing the property `pagecomponents` on the result of `resolve()`.

We simply fixed it by renaming `pagecomponent` to `page_component`.

**Comment by kevinvdburgt** [comment]
That is a really nice explanation! As far i know GraphQL doesn't query any databases if you don't return or use a model inside the resolve function.

But the issue sure seems strange, I will try to reproduce this issue later to check out what is going on.

**Comment by kikoseijo** [comment]
I think you had a cache issue resolved at the same time you changed the name of the property.
Makes no sense to change a connection name, what you did its to change the relationship name, this is more to do with Laravel.

Anyways, glad you found your problem-

**Comment by pSchaub** [comment]
@kevinvdburgt @kikoseijo I updated the above explanation. The important thing is to name the model method the same as in the type. It's case-sensitive. You can rename it thanks to the `resolve` feature. I explained it above.

If it's not the same you will fall into a bug once you use caching. If you don't do caching you will never see that kind of issue.

**Comment by kevinvdburgt** [comment]
Could you create an example project, tried to reproduce your issue but it worked fine for me.

**Comment by drmax24** [comment]
It is not clear for me how can I cache output result of a complex query.
Let's say I query car accessories together with related cars and other related stuff:

```
    public function resolve($root, $args, $context, $info)
    {
...
 $result = Accessories
                ::where($where)
                ->get();

        if (Cache::store('redis')->has('all_accessories')) {
            $result = Cache::store('redis')->get('all_accessories');
        } else {
            Cache::store('redis')->put('all_accessories', $result, 10080);
        }

return $result;
    }
```

If I cache it like this then all relations won't be cached. Because the result does not contain any of them 
 at the moment of caching.

**Comment by mfn** [comment]
Is your example correct? It looks like you're always fetching via Eloquent and only storing data but never retrieve from the cache?

I guess I would have expected something like:
```php
return Cache::remember('all_accessories', function () use ($where) {
  return Accessories::where($where)->get();
});
```


> If I cache it like this then all relations won't be cached. Because the result does not contain any of them
> at the moment of caching.

In that case you have figure out yourself:
- what relations do I need?
- eager load them
- if you want them cached too => you need to basically create a big nested datastructure (an array would suffice, I guess) and cache/return it (and maybe adapt some other resolvers)

But maybe the problem somewhere else? E.g. slow query because of missing/bad index? Just fishing here.

GraphQL, in general but also this wrapper, is very thin and doesn't know anything about where your data comes from. It only processes what you return from the resolver (or: default resolver!, be aware of that). As such, it's up to you have to retrieve/cache this information.

If you've trouble with this approach you can also look into more advanced concepts like DataLoader [1] which can help mitigating n+1 or caching problems.

[1] https://github.com/overblog/dataloader-php
