### ISSUE TITLE
[Proposal] Artisan commands to make Type and Query

### ISSUE THREAD

**Issue by alnutile** [Folkloreatelier/laravel-graphql#31]
Was going to work on this next week or the week after as we use this tool in a project.

The commands would, like other generators, allow the user to make the model from the command line.

```
php artisan make:graphql:type UserType
```

That would then make the files, folders if needed, and update the config file as well.

```
php artisan make:graphql:query UsersQuery
```

Same here.

The user would fill in the args and resolve though later can add options.

Let me know if this is not something already in your planning and I will continue on with it.

Thanks!

**Comment by SimonErich** [comment]
@alnutile  you might want to look at:
https://github.com/nuwave/laravel-graphql-relay
It has generators for types, queries, fields and mutators built in and also supports relay.

**Comment by dmongeau** [comment]
This is in the v1 (currently in the v1 branch) which will be released soon.

**Comment by alnutile** [comment]
nice! thanks
