### ISSUE TITLE
Infinite Loop With Lists and Relations

### ISSUE THREAD

**Issue by mohamed-alashry** [Folkloreatelier/laravel-graphql#32]
Hi, I've encountered an issue that results in an infinite loop and a segmentation fault with trying to use lists to definite simple relationships versus a Relay connection. Is there something I'm doing incorrectly for this situation or is this an issue? I could use a connection though in this use case there at most are 1-2 related objects so a connection is overkill and a list would be more appropriate.

I have a SessionType which has a list of payments for the one-to-many relationship. In relayFields() I'm returning this for payments:

'payments' => [
    'type' => Type::listOf(GraphQL::type('payment')),
    'description' => 'Payments for session',
    'resolve' => function (Session $session) {
        return $session->payments;
    }
],
In my PaymentType I then have the inverse:

'session' => [
    'type' => GraphQL::type('session'),
    'description' => 'Session that payment is connected to',
    'resolve' => function (Payment $payment) {
        return $payment->session;
    }
],
This results in an infinite loop since it is trying to create the PaymentType while trying to create the SessionType which then repeats the process resulting in a loop

@davidstoker

**Comment by davidstoker** [comment]
@mohamed-alashry, why did you copy the text of my [issue](https://github.com/nuwave/laravel-graphql-relay/issues/20) from a different library over to this library?
