### ISSUE TITLE
Is there a better way to resolve fields using methods without calling public attributes?

### ISSUE THREAD

**Issue by marcelofuchs** [Folkloreatelier/laravel-graphql#326]
Is there a better way to resolve fields using methods without calling public attributes?

- Example type:

`<?php

namespace App\GraphQL\Type;

use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\Type as BaseType;

class CompanyType extends BaseType
{
    protected $attributes = [
        'name' => 'Company',
        'description' => 'Change Companies'
    ];

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'description' => 'String not null'
            ],
            'name' => [
                'type' => Type::nonNull(Type::string()),
                'description' => 'String not null'
            ],
            'active' => [
                'type' => Type::nonNull(Type::boolean()),
                'description' => 'If Company is active'
            ],
            'createdAt' => [
                'type' => Type::string(),
                'description' => 'When Company is created'
            ],
            'updatedAt' => [
                'type' => Type::string(),
                'description' => 'When Company is updated'
            ]

        ];
    }

    protected function resolveNameField($root, $args)
    {
        return $root->getName();
    }

    protected function resolveActiveField($root, $args)
    {
        return $root->getActive();
    }

    protected function resolveIdField($root, $args)
    {
        return $root->getId();
    }

    protected function resolveCreatedAtField($root, $args)
    {
        return $root->getCreatedAt()->format('Y-m-d H:i:s');
    }

    protected function resolveUpdatedAtField($root, $args)
    {
        return $root->getUpdatedAt()->format('Y-m-d H:i:s');
    }

}
`

**Comment by dmongeau** [comment]
You can also add a `resolve` key to your fields declaration.

```php
public function fields()
{
    return [
        'id' => [
            'type' => Type::nonNull(Type::id()),
            'description' => 'String not null',
            'resolve' => function($root) {
                return $root->getId();
            }
        ],
        'name' => [
            'type' => Type::nonNull(Type::string()),
            'description' => 'String not null'
        ],
        'active' => [
            'type' => Type::nonNull(Type::boolean()),
            'description' => 'If Company is active'
        ],
        'createdAt' => [
            'type' => Type::string(),
            'description' => 'When Company is created'
        ],
        'updatedAt' => [
            'type' => Type::string(),
            'description' => 'When Company is updated'
        ]

    ];
}


```
