### ISSUE TITLE
Proper way to delete items

### ISSUE THREAD

**Issue by livemixlove** [Folkloreatelier/laravel-graphql#34]
Hi there,

Forgive me if this is dead obvious.  When I delete a row and then try to return it in a mutation, I get the error "Cannot return null for non-nullable type", presumably because something on the backend is querying a now deleted row.   I can work around this by setting a type property return value to nullable, but then I get a null return values.  

I want to return the object that I'm deleting.    Or, at least return the id.  Is this possible?

something like 
mutation  deleteThing(thing_id: 2){ thing_id}

or even just

mutation deleteThing(thing_id: 2){ message }

Ideas for doing this?

Thank you!  (and I suppose this is more a request for documentation than anything)

**Comment by dmongeau** [comment]
Yes your mutation could look like this:

```php
namespace App\GraphQL\Mutation;

use GraphQL;
use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\Mutation;    
use App\User;

class DeleteThingMutation extends Mutation {

    protected $attributes = [
        'name' => 'DeleteThing'
    ];

    public function type()
    {
        return GraphQL::type('thing');
    }

    public function args()
    {
        return [
            'thing_id' => ['name' => 'thing_id', 'type' => Type::nonNull(Type::string())]
        ];
    }

    public function resolve($root, $args)
    {
        $thing = Thing::find($args['thing_id']);
        if(!$thing)
        {
            return null;
        }
            
        $deletedThing = $thing->toArray();
        $thing->delete();

        return $deletedThing;
    }

}
```
