### ISSUE TITLE
Best practive to have graphiql enabled in dev but not production?

### ISSUE THREAD

**Issue by mfn** [Folkloreatelier/laravel-graphql#351]
I'm wondering because the default `config/graphql.php` is expected to be like:
```php
    /*
     * Config for GraphiQL (see (https://github.com/graphql/graphiql).
     * To disable GraphiQL, set this to null
     */
    'graphiql' => [
        'routes' => '/graphiql/{graphql_schema?}',
        'controller' => \Folklore\GraphQL\GraphQLController::class.'@graphiql',
        'middleware' => [],
        'view' => 'graphql::graphiql',
        'composer' => \Folklore\GraphQL\View\GraphiQLComposer::class,
    ],
```
and e.g. in `routes.php` we've this: https://github.com/Folkloreatelier/laravel-graphql/blob/171631a17e4bf33780513f15221ea6052c67d498/src/Folklore/GraphQL/routes.php#L106-L107

I don't see an easy way to use e.g. `env('GRAPHGL_GRAPHIQL', false)` somewhere so I can use `.env` to easily switch it on/off.

The config key `graphql.graphiql` is a somewhat "complex" array which I can't provide via an environment variable.

Is it possible to introduce a config key like `graphql.graphiql.enabled` and use this in the library?

That way the whole graphiql setup configuration can be kept but a single variable can then be used to switch it.

Thanks

**Comment by kevinvdburgt** [comment]
You can make a middleware for the GraphQL route to check the env()

**Comment by mfn** [comment]
Works for me 👍 

Still think it would make sense to have a more specific/easier way to disable it without throwing away the whole configuration!
