### ISSUE TITLE
How to resolve type fields with query args

### ISSUE THREAD

**Issue by BRKsReginaldo** [Folkloreatelier/laravel-graphql#357]
Hello guys, first of all, thank you for this awesome package witch makes our lives a lot easier.

So, i have a many-to-many relatonships between my user and a market wich i call "favorited_markets", the relationship is fine, the mutations for add and remove market from favorites too, but now, i would like to know how can i query a field like "is_favorite" on the market type ? 

For example: 

```graphql
query markets(
$user_id: ID!
) {
    markets(user_id: $user_id) {
        id,
        name,
        is_favorite # This is the part wich i want to know based on the user_id
    }
}
```

on my MarketType class i have the following method

```php
public function resolveIsFavoriteField($root, $args) {
  // how can i get the user_id passed on the query for check if 
  // the relationship between the user and the market exists ?
}
```

sorry for my bad english, brazilian guy

**Comment by mfn** [comment]
> sorry for my bad english, brazilian guy

Don't worry, it's great! 🇧🇷  :-)

> i would like to know how can i query a field like "is_favorite" on the market type ?

Unfortunately I don't understand it completely. Does your `Market` model (eloquent) has this field? Or how do you calculate it?

When I read this:
```graphql
markets(user_id: $user_id) {
        id…
```
My understanding would be that your solve markets via something like `Market::whereUserId(…)` which gives you back a collection and should have loaded all your fields, including `is_favourite` already.

Or is `is_favourite` calculated special on the Eloquent model?

**Comment by BRKsReginaldo** [comment]
sorry if I did not explain it well.

This is my scenario:

I have a user model with the following fields: id, name, email, password
And a market model with the following fields: id, name, and the products relationship (wich is not important here)
And a pivot table named favorited_markets with the following fields: user_id, market_id

The is_favorite field doesn't exists anywhere, is just a method that returns the existense of the relationship between the user and the market on   favorited_markets table

The thing is that i don't know how can i calculate this for every market before returning the query result, i tought that using the syntax resolveCustomField on the MarketType could help me, if i had access to the args passed on the query, this problem would be solved

**Comment by mfn** [comment]
Ah, I think I understand.

Note sure if its the best way, I solved a similar problem by eager loading this information in the `resolve` method of the _query_, not the type.

In my case, I did load attachment for posts. But since I was trying to load n attachment on m posts, it needed eager loading otherwise I would suffer from a classical `n + 1` DB problem.

Because in the `resolve` of the query, I can access the fields being requested. The last parameter `ResolveInfo` has a method `getFieldSelection` with a depth parameter, returning a plain nested array with which you can "peek".

Maybe that what you can pre-load this information?

**Comment by mfn** [comment]
See https://github.com/Folkloreatelier/laravel-graphql/blob/master/docs/advanced.md#eager-loading-relationships

**Comment by BRKsReginaldo** [comment]
Great! Many thanks, you helped me a lot
