### ISSUE TITLE
Difference between Type and Field?

### ISSUE THREAD

**Issue by edalzell** [Folkloreatelier/laravel-graphql#362]
I’m trying to create a GraphQL implementation on top of a CMS and I need a composite type/field but I’m unsure which I need. 

Is there a description of when to use a Field and when to use a Type?

**Comment by mfn** [comment]
Can you explain in more detail this part ?
> composite type/field

Maybe it helps to read up the GraphQL specs
- http://facebook.github.io/graphql/June2018/#sec-Types
- http://facebook.github.io/graphql/June2018/#sec-Field-Arguments

In probably completely wrong term: a type is like a table/class and a field is like a column/property.

Does that help?

**Comment by edalzell** [comment]
the CMS I'm trying to build upon has a Fieldtype called Grid, which contains and array of arbitrary "columns" or fields. So I'd like to represent that. I have this so far:
```
           case 'grid':
                return Type::listOf(GraphQL::type('Row'));
                break;
```

And `RowType` will contain those arbitrary fields (which I need to get from the CMS config). 

Should Row be a Type or a Field? You would never query for a Row on it's own, only as part of a larger Type (User, Collection, Page, etc).

**Comment by edalzell** [comment]
but the row may also contain other grids, etc.

**Comment by mfn** [comment]
The way I understood it, it's a type; like you already said yourself "And Row**Type** will…"

From what I see in your code example, the `grid` is the field and the underlying structure is the type.

**Comment by edalzell** [comment]
OK, thanks.
