### ISSUE TITLE
No graphql.php

### ISSUE THREAD

**Issue by softwareishappiness** [Folkloreatelier/laravel-graphql#368]
After installing there is no graphql.php file to be found. I am unable to review the file and configure. Below is the step from your README.md

> 2- Review the configuration file
> 
> config/graphql.php

Using Laravel 5.6

**Comment by mohammad-fouladgar** [comment]
Try this one:
```bash
php artisan vendor:publish --provider="Folklore\GraphQL\ServiceProvider"  --tag="config"
```

**Comment by softwareishappiness** [comment]
Perfect! Thank you 👍
