### ISSUE TITLE
Status codes for error handling

### ISSUE THREAD

**Issue by nicholas-littlelives** [Folkloreatelier/laravel-graphql#37]
I like how the graph-php and this package catch errors during the query and places the message in the payload. It does not however preserve the response status code set or $code attribute in the error object.

Any chance this can be done?

**Comment by dmongeau** [comment]
Yes, I have added a config parameter to use a custom error formatter so you can add whatever you want to the error object returned by GraphQL. See `error_formatter` in  https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/config/config.php . You will need to update to v0.4.4 .

You can check the formatError method in https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQL.php as a starting point.
