### ISSUE TITLE
it doesn't work with Laravel 5.7

### ISSUE THREAD

**Issue by aymenbz** [Folkloreatelier/laravel-graphql#376]
Laravel 5.7 has been released and this package doesn't support it yet.
so any plans to update the package ?

**Comment by SonarSoftware** [comment]
I submitted a PR for it, hopefully it will get merged soon.

**Comment by mfn** [comment]
> I submitted a PR for it

Not quite, you simple slapped it onto an existing PR you're working on ( https://github.com/Folkloreatelier/laravel-graphql/pull/295 ) . There's no dedicated PR to upgrade the dependencies.

But given the activity here it's questionable what will happen here anyway.

**Comment by SonarSoftware** [comment]
Yeah, it's been pending so long I have been using my fork for months
anyway. Probably going to just hard fork soon and update to the new webonyx
library and drop support for older Laravel.

**Comment by hanspagel** [comment]
Isolated your commit and created a new pull request.

**Comment by hanspagel** [comment]
To use the Laravel 5.7 compatible fork add this to your composer.json:

    {
        …
        "repositories": [
            {
                "type": "vcs",
                "url": "https://github.com/heyscrumpy/laravel-graphql"
            }
        ],
        "require": {
            "folklore/graphql": "dev-develop",
            …
        }
    }

**Comment by bkuhl** [comment]
https://github.com/Folkloreatelier/laravel-graphql/pull/378 has been merged into `develop`

**Comment by spawnia** [comment]
If you are looking for an actively maintained integration of GraphQL into Laravel, take a look at https://github.com/nuwave/lighthouse/

We support Laravel 5.7, have a [Slack channel](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWI1ZDQ1YWM1NmM2MmQ0NTU0NGNjZWFkMTJhY2VjMDAwZmMyZDFlZTc1Mjc3ZGY0MWM1Y2Q5MWNjYmJmYWJkYmU) and a nice [docs website](https://lighthouse-php.netlify.com/)

**Comment by aymenbz** [comment]
Thanks All 👍
