### ISSUE TITLE
JSON value

### ISSUE THREAD

**Issue by mxmtsk** [Folkloreatelier/laravel-graphql#38]
Hey,

I wanna know how I can give back a string as an actual json object and not as an escaped string from a table's column? Is there a way to achieve this?

**Comment by dmongeau** [comment]
You mean this http://stackoverflow.com/questions/7282755/how-to-remove-backslash-on-json-encode-function/22648879#22648879 ?

**Comment by dmongeau** [comment]
Closing this.

**Comment by tremby** [comment]
I think in fact he was asking about how to return a JSON value as an object rather than as a string. It looks like setting up an ObjectType might do the job.

**Comment by MCON** [comment]
>>I think in fact he was asking about how to return a JSON value as an object rather than as a string
yup. I need this too.
What ObjectType there is no any.

**Comment by tremby** [comment]
https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/ObjectType.php

**Comment by dmongeau** [comment]
Yes, your `image_file_names` should be a field of type ObjectType defining the subfields instead of a `Type::string()`. This way you can have multilevel object.
