### ISSUE TITLE
error-message: Cannot query field users on Query

### ISSUE THREAD

**Issue by RichardForrester** [Folkloreatelier/laravel-graphql#4]
Thank you for your work on this package. I am very excited to use.

I am sorry to make an issue but I'm just learning relay (as most are atm) and I followed your instructions on the readme exactly however I get the following error message when visiting my .../graphql?query=query+FetchUsers{users{id,email}} .

`{
    "errors": [
    {
        "message": "Cannot query field users on Query",
"locations": [
{
"line": 1,
"column": 18
}
]
}
]
}`

Error message isn't very helpful to me and I'm not sure where to look to dig deeper. I'm on Ubuntu 15.04, Laravel 5.* using Homestead VM.

**Comment by dmongeau** [comment]
Hello,
No problem. Could you copy the content of your `config/graphql.php` ?

**Comment by RichardForrester** [comment]
I actually fixed the problem. I think it had something to do with the fact that I haven't completely switched over to PSR-4 name spacing yet or possibly I just had a plural/singular mistake in the code or name space. I had to add `use Folklore\GraphQL\Support\Query;` to the UsersQuery.php. Thanks again. Time to start adding some React and Relay to my Laravel site!!!
