### ISSUE TITLE
query and mutation executing twice

### ISSUE THREAD

**Issue by mikefrancis** [Folkloreatelier/laravel-graphql#402]
I am testing a graphql query through Insomnia and for some reason it is executing twice - whether it's a query or a mutation, I always see the execution time populate, then change (and 2 rows created in the DB if it's a create mutation).

I have another graphql project written in JS which works fine, so it doesn't seem to be Insomnia that is the problem.

AFAIK my code looks ok, it's adapted from the examples.

Do you know where I can start debugging this? Maybe I don't have the project installed properly 🤔

Here's my versions:

- Laravel 5.7.17
- This package 1.0.9

**Comment by mfn** [comment]
> Do you know where I can start debugging this?

I would use xdebug, set a breakpoint; should be fairly easy to pinpoint this.

**Comment by mikefrancis** [comment]
Just reinstalled everything, working now! Very strange. Thanks for your help!
