### ISSUE TITLE
GraphQL Error: Variable of type "String" used in position expecting type "String!"

### ISSUE THREAD

**Issue by filipenatanael** [Folkloreatelier/laravel-graphql#405]
Hello Everyone!

So I'm getting the error below when I try to retrieve values from the endpoint.

> GraphQL error: Variable "$id" of type "String" used in position expecting type "String!".

The same is happeinig when I try to use **Int!** as well.

**Below is the code:**

*UserQuery.php*
```php
  public function args()
  {
    return [
      'id' => [
        'type' => Type::nonNull(Type::string())
      ]
    ];
  }
```

*User.gql* 
```gql
query User($id: String) {
  user(id: $id){
    name
    email
  }
}
```

**Comment by mfn** [comment]
This `Type::nonNull(Type::string())` is a **required** field, i.e. it can't contain `null`.

That GraphQL DSL idiom is to write this as `String!` (the `!` is the same as `Type::nonNull()`)

But in your query, you simple wrong `$id: String` when it should have been `$id: String!`; the types _must match_.

Probably the same for your "int" issue.

**Comment by filipenatanael** [comment]
@mfn Thanks for your help

I was able to resolve adding the code below:

```php
// laravel-graphql/config/graphql.php
'params_key' => 'variables',
```
I also had to adjust some things in the lib(apolloClient) that I was using in frontend application.

Thank you again :)
