### ISSUE TITLE
custom field

### ISSUE THREAD

**Issue by mitjarobic** [Folkloreatelier/laravel-graphql#41]
If i use a class path to custom field i get

"message": "Undefined index: type",
  "status_code": 500,
  "debug": {
    "line": 110,
    "file": "/var/www/laravel/plugins/robocode/api/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php",

**Comment by trihatmaja** [comment]
https://github.com/Folkloreatelier/laravel-graphql/pull/44

i already fix the example..
