### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mxmtsk** [Folkloreatelier/laravel-graphql#45]
I have a very generic question: How would you deal with protected queries? I don't really see a good way to implement it in any way? Is it possible that someone gives me an hint or an example?

(I'm using tymondesigns/jwt-auth for token based authentication in Laravel)

**Comment by rhenann** [comment]
+1

**Comment by dmongeau** [comment]
In the config there is a `'middleware'` setting where you could add the `auth` middleware if you want to protect graphql.

With v0.4.6, you could also define a route that use a different schema than the one in the config. Something like this:

The Controller:
```php
<?php namespace App\GraphQL;

use Illuminate\Routing\Controller;
use Illuminate\Http\Request;

class GraphQLController extends Controller {
    
    public function query_auth(Request $request)
    {
        $query = $request->get('query');
        $params = $request->get('params');
        
        if(is_string($params))
        {
            $params = json_decode($params, true);
        }

        //Either put your schema in the config or define it here
        $authSchema = config('graphql.schema_auth', [
            'query' => [
                //Put your protected queries
            ],
            'mutation' => [
                //Put your protected mutations
            ]
        ]);
        
        return app('graphql')->query($query, $params, $authSchema);
    }
    
}

```

And define the protected route
```
Route::get('/graphql', [
    'middleware' => ['auth'],
    'uses' => 'GraphQLController@query_auth'
]);

**Comment by mxmtsk** [comment]
@dmongeau Thanks, the middleware for all isn't suitable for me (as I have public routes) but the 2nd option is working for me! Thanks :)

**Comment by tafint** [comment]
i use middleware 'auth:api' in schemas but not get effect. how to use middleware in graphql config right way?
