### ISSUE TITLE
Upstream changed, breaks examples on readme

### ISSUE THREAD

**Issue by nokios** [Folkloreatelier/laravel-graphql#46]
I am getting the following error when following the examples you have written out on the readme.

> ErrorException in Schema.php line 61:
> GraphQL\Schema constructor expects config object now instead of types passed as arguments. See https://github.com/webonyx/graphql-php/issues/36

You need to make `folklore/graphql/src/Folklore/GraphQL/GraphQL.php:70` send an array in the form of this:
```return new Schema(['query' => $queryType, 'mutation' => $mutationType]);```

**Comment by dmongeau** [comment]
Yes, there was some breaking changes in webonyx/graphql-php v0.7.0, I've updated version v0.4.9 so it uses v0.6.0 until I made the changes to support v0.7.0.

**Comment by dmongeau** [comment]
I'm in the process of adding Unit Tests, so hopefully if will prevent those problems in the future.

**Comment by nokios** [comment]
Cool.  I like what GraphQL has to offer.. interested in seeing this project grow.
