### ISSUE TITLE
Unique Validation

### ISSUE THREAD

**Issue by mxmtsk** [Folkloreatelier/laravel-graphql#47]
I'm using a graphql mutation to change a users email adress. Therefore I use the rule() method in my mutation but I need to pass the user id to the "unique" validation rule so that it ignores the user on updating. 

How can I achieve this or is this not supported?

**Comment by dmongeau** [comment]
The current logged in user? If yes, you could access the `Auth::user()->id`. If not, the new version I'm working on, is implementing the `context` of webonyx/graphql-php v0.7.0, which is made available in every type and queries and would work for that particular case.

**Comment by belohlavek** [comment]
Hey @dmongeau, how's this coming along?

**Comment by dmongeau** [comment]
It's released as 1.0!

**Comment by ebbbang** [comment]
What if I want to validate uniqueness on something else and ignore itself on update ...
The ID is in the args and I cant access it in rules function example.

Ex:

```php
public function args()
{
    return [
        'id' => ['name' => 'id', 'type' => Type::nonNull(Type::int())],
        'name' => ['name' => 'name', 'type' => Type::nonNull(Type::string())],
    ];
}

public function rules()
{
    return [
        'id' => ['required', 'exists:movie_genres,id'],
        'name' => ['required', Rule::unique('movie_genres', 'name')->ignore('How to get ID from the args passed here ?')],
    ];
}
```

**Comment by ktogo** [comment]
@ebbbang I've submitted a PR to solve this: #126

Please leave a comment there if you have any thoughts :)

**Comment by ktogo** [comment]
Oops I replied to wrong PR. Please ignore above comment!

**Comment by bdebever** [comment]
Hi, 
@ebbbang , have you found any workaround for that? 

thanks;

**Comment by pSchaub** [comment]
@bdebever @ebbbang  The _rules()_ function already has the $args as function parameter. You need to use "func_get_args()" to get access to them. I think this should be improved, see https://github.com/Folkloreatelier/laravel-graphql/issues/240
