### ISSUE TITLE
Config keys and Query names are diverging

### ISSUE THREAD

**Issue by ChristophP** [Folkloreatelier/laravel-graphql#48]
I have noticed that the current implementation has bit of an ambiguity when it comes to the names of  Queries(maybe types also). Let me illustrate that.

In my config I have:
```
'schema' => [
  'query' => [
    'usersQuery1' => 'App\GraphQL\Query\UsersQuery',
  ],
],
```
So when I query I need to use the name of the query like this.
```
query test {
  usersQuery1 {
    name
  }
}
```
However I still have the option to specify the query name inside the Query itself:
```
namespace App\GraphQL\Query;

class UsersQuery extends Query {

  protected $attributes = [
    // this name is returned for introspection queries
    'name' => 'usersQuery2',
    'description' => 'Query to fetch the user type',
  ];

  ...
}
```

So which one of the names is actually used? I was using the GraphiQL and it becomes obvious quickly that both are. I can only use `usersQuery1` to query the data. But when I issue an introspection query (or open the docs in in GraphiQL) I get `usersQuery2`. This also breaks autocompletion in GraphiQL.

Is this something that anyone else noticed or has had issues with? Do you think it is worth fixing? As a workaround I am using the same name in the config and the query but I think it is bad practice and error prone to have the same name in two places. My suggestion would be to use the name of the Query if it is given and only use the key that is used in the config otherwise. What do you think of that?

**Comment by dmongeau** [comment]
Thanks for noticing that. I'm in the process of writing Unit Tests and while I'm doing it, I came accross this irregularity. In my opinion, the name you put in the config should have precedence on the name in the Query, so you could overwrite it and even uses the same Query two times with different name. This is what I'm going to implement for Query, Mutation and Type. So everything works the same. 

What you think?

**Comment by ChristophP** [comment]
Hey, thanks for your quick reply. I think the most important thing is that there is one single source of truth (because now both values are used). It doesn't matter that much to me which one gets the precedence but I do have a couple of questions about what you said.
1.
`In my opinion, the name you put in the config should have precedence on the name in the Query, so you could overwrite it ...`.
If you want to override the value form the config that means that normally you don't specify the name in the config. But usually you specify the key all the time when you add a query.
```
'schema' => [
 'usersQuery' => 'App\GraphQL\Query\UsersQuery', 
]
```
so if you want to leave that out you might want to add a way to add queries in non-associative arrays and then have the name taken from the name prop of each query object.
```
'schema' => [
  'App\GraphQL\Query\UsersQuery', 
]
```
From the source code it didn't look like non-associative arrays are already implemented. So I think you should implement that or do it the other way around, namely use the name prop in the Object to override the key in the config(I think this is already implemented for types in the `addType()` method). It could be done analogous to that. I hope I don;t sound too confusing :-) What do you think?  
2.
`... and even uses the same Query two times with different name.`
I think using the same query with the same name is not necessary and leads to confusion since I believe the query name should be somewhat unique throughout the GraphQL Service. Or do you have a specific reason for that?

**Comment by ChristophP** [comment]
Hey @dmongeau do you have any more thoughts on my reply? Do you have a rough time frame when this fix will be available in the future?

**Comment by dmongeau** [comment]
Right now it is available on the v1 branch, I'm finishing the unit tests. You can test if the behavior is what you expected. Let me know.

Should be released in a week!

**Comment by ChristophP** [comment]
Ah cool I will check it out.

**Comment by ChristophP** [comment]
So I installed the version `v1.x-dev` from composer and tried it out. Works, really well.
The only think I could add is that this you could add to the readme which name takes precedence but other than that the version looks really nice overall. Good work. :+1:

**Comment by ChristophP** [comment]
I guess I can close this issue. Since the changes with be merged soon.
