### ISSUE TITLE
Laravel 4.2 support?

### ISSUE THREAD

**Issue by inakianduaga** [Folkloreatelier/laravel-graphql#5]
I quickly browsed through the code and didn't seem to find anything that wouldn't work on 4.2. 

Is the 5.0 requirement due to something failing on 4.2 or did you just ignore 4.2 from the start?

**Comment by dmongeau** [comment]
I didn't plan to support Laravel 4.2 but I'm sure it's definitely possible. I will accept a pull request for Laravel 4.2 support if anyone wants to do it.

**Comment by inakianduaga** [comment]
good to know, thanks
