### ISSUE TITLE
Custom field return type null

### ISSUE THREAD

**Issue by CapMousse** [Folkloreatelier/laravel-graphql#50]
When asking GraphQL to build the schema of a type, custom field using `Type::listof(. . .)` return a null type

Request : 

    {  
      __type(name: "User") { 
        name 
        fields { 
          name 
          type { 
            name 
          } 
        } 
      } 
    }

Reponse :

    {
      "data":{
        "__type":{
          "name": "User",
          "fields":[
            {"name": "followings", "type":{"name": null }},
          ]
        }
      }
    }

**Comment by dmongeau** [comment]
Tested and this is a bug with https://github.com/webonyx/graphql-php when using Type::listOf

**Comment by dmongeau** [comment]
@CapMousse see webonyx/graphql-php#63 for explanation.
