### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by belohlavek** [Folkloreatelier/laravel-graphql#55]
Is there any way to set the HTTP status code from the `resolve()` method? I know GraphQL can return "partial success", but it'd be nice to be able to take advantage of the tool that HTTP provides us 😀

**Comment by dmongeau** [comment]
I don't think the resolve method should deal with any HTTP concerns since GraphQL can be used without any HTTP query. But I'll check the specs for the status code it should return when an error occured when used with the controller.
