### ISSUE TITLE
Eager loading relationships

### ISSUE THREAD

**Issue by brayniverse** [Folkloreatelier/laravel-graphql#6]
When resolving a query is it possible to get the list of types requests in order to eager load Eloquent relationships?

**Comment by TheGhoul21** [comment]
public function resolve($root, $args, GraphQL\Type\Definition\ResolveInfo $info)
    {

        $request = ($info->getFieldSelection(3));
        ...
    }

*$request* will contain an array of the fields required. If there's a subselection there will be an array of fields

**Comment by brayniverse** [comment]
That works perfectly thank you.
