### ISSUE TITLE
Add query complexity/dept config option ?

### ISSUE THREAD

**Issue by pelletiermaxime** [Folkloreatelier/laravel-graphql#60]
Hi, first of all thanks for the great package.

What do you think about adding config options for the QueryComplexity and QueryDept rules of graphql-php ? I know I can set them in my bootstrap for example :

``` php
$queryComplexity = DocumentValidator::getRule('QueryComplexity');
$queryComplexity->setMaxQueryComplexity($maxQueryComplexity = 1);

$queryDepth = DocumentValidator::getRule('QueryDepth');
$queryDepth->setMaxQueryDepth($maxQueryDepth = 1);
```

But I think adding options in config/graphql.php would be more user friendly. What do you think ? If you think it's a good idea I could send a PR.

Thanks.

**Comment by dmongeau** [comment]
Yes, we could add this in the config, with `null` as the default value and set this in the ServiceProvider if the value is other than null just to be sure it doesn't have any impact on people that doesn't need to explicitly set this. A PR would be much appreciated

**Comment by dlai286** [comment]
@dmongeau any chance you can accept and merge the PR?

**Comment by dmongeau** [comment]
Sorry about that, merged!
