### ISSUE TITLE
per type field authorization

### ISSUE THREAD

**Issue by leemason** [Folkloreatelier/laravel-graphql#63]
thanks for such a great package, however im a bit stuck for how to authorize access to specific fields from a model.

consider you have a model "reservations" which has the fields "table", "time", "person".

if i query a reservation and I AM NOT the owner of the reservation, or an admin i should only be able to return "table" and "time", even if the query requests "person".

how would you consider handling this?

**Comment by dmongeau** [comment]
First you can look at http://graphql.org/learn/authorization/

Basically you could check if the user as the right with any mechanism you want (like Laravel Policies) and return null if the user cannot view a particular field. Another possibility, which I'm not sure if it will works is to use the ResolveInfo (like in this example https://github.com/Folkloreatelier/laravel-graphql/blob/master/docs/advanced.md#eager-loading-relationships) and throw an error if there is an unauthorized field in the query.

But I guess your question was, can the field be not present if the user doesn't have the right? I don't think it's possible, GraphQL is meant to return the data exaclty like your query, so if your person field is there in the query, it makes sense that it will be there in the results.

**Comment by leemason** [comment]
thanks for quick and detailed response, yes i was thinking about policies etc, and also oauth scopes when using passport.

from the spec all ive found in the http area is:

> A response may contain both a partial response as well as encountered errors in the case that an error occurred on a field which was replaced with null.

i think its clear IF they arent authorized to view a field and they request it, to satisfy the spec it must still be included with a null value (as already happens).

however from the quote above it suggests i should add an error to the response, explain why the field is null.

It think that makes sense (a little more in the spec would be better, but i know thats not for this package to maintain).

Now i need to figure out how to attach additional errors to the response?

it looks like i need to throw a `\GraphQL\Error\Error`, but theres a few things im unsure of:

1. it looks like this error needs source and source location data, how would i get that information in the resolve callbacks?
2. once i throw this error (looking at the source) it will be caught and added to the response, which is perfect .... if theres only one instance of this error occuring (i think).

if there are multiple fields requested that have this type of error im not sure if your package could catch and add these, or if i need to go the underlying repo and see what they say?

**Comment by leemason** [comment]
just a quick update for others to reference (untested, yet).

more investigation appears to the answer the questions above: https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L510

When each field is resolved it is wrapped in a try catch block and if an error is thrown the source information is then added to the response. so it appears we can just throw an error and null value will be used AND an error will be added to the response.

This is on a per type > field basis, i havent looked into query resolve functions, but i would assume the same is true (eg, if a user cannot request a collection of other users, throw and error and it will be added to the response).

i will be trying this soon, and once confirmed maybe the readme should be updated (here and on the underlying project) to make an example of throwing an error in a resolve function.

**Comment by dmongeau** [comment]
Closing this since it has been added
