### ISSUE TITLE
Unable to get auth middleware working

### ISSUE THREAD

**Issue by nharlow89** [Folkloreatelier/laravel-graphql#66]
Has anyone successfully added auth middleware to the `graphql` endpoint? I am working on a clean `Laravel 5.3` installation. Auth middleware is working for the rest of the app. GraphQL (and GraphiQL) are integrated and working fine. When I try adding:
```
'middleware' => [ 'auth' ]
```
to my `graphql.php` config file I cannot seem to get past the un-authenticated response.

**Comment by dmongeau** [comment]
What kind of authentication? If it uses sessions, you might need the middleware for it since GraphQL routes are not added in the 'web' middleware group by default.

**Comment by nharlow89** [comment]
Just what I needed thanks @dmongeau. In case anyone else is stuck on this, I had to create another `middlewareGroup` in `app/Http/Kernal.php`
```php
'graphql' => [
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
    \Illuminate\Session\Middleware\StartSession::class,
],
```
and then in `config/graphql.php` add the new `middlewareGroup` along with the auth middleware
```php
// Any middleware for the graphql route group
'middleware' => [ 'graphql', 'auth' ],
```

**Comment by 2Fwebd** [comment]
Thanks @nharlow89 !!! After 2 hours, that fixed my issue! For those wondering, why 
`Auth::user()` returns `null`, that's it!
