### ISSUE TITLE
how to send request in graphql

### ISSUE THREAD

**Issue by xcaptain** [Folkloreatelier/laravel-graphql#68]
I'm following the readme to setup my first graphql API, but I come across some issues.

according to https://github.com/Folkloreatelier/laravel-graphql#creating-a-query , this should return a response when invoking `http://homestead.app/graphql?query=query+FetchUsers{users{id,email}}
` but I my lumen 5.3.2 project it just returned a 404 not found.

noticing that in [routes.php#L64](https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/routes.php#L64) there is no router for get requests, So I suggest whether change the readme file that use a post request, like:
```bash
curl 'http://homestead.app/graphql/' --data 'query=query+FetchUsers{users{id,email}}'
```

or add
```php
$router->get(preg_replace($schemaParameterPattern, '', $queryRoute), array(
        'as' => 'graphql.query',
        'uses' => $queryController
));
```
in [routes.php](https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/routes.php)

**Comment by dmongeau** [comment]
You are right, I will add the get route!
