### ISSUE TITLE
graphiql not found

### ISSUE THREAD

**Issue by belohlavek** [Folkloreatelier/laravel-graphql#69]
https://unpkg.com/graphiql@0.7.8/graphiql.min.js
Not found: file "/graphiql.min.js" in package graphiql@0.7.8

v0.8.0 works: https://unpkg.com/graphiql@0.8.0/graphiql.min.js

Should look into some way of getting a stable source for those files! (maybe ship with a specific graphiql version?)

**Comment by pelletiermaxime** [comment]
Weird, https://unpkg.com/graphiql@0.7.8/graphiql.min.js works for me. I used a CDN for everything to keep the git repo small. You can always override the template if you want to lock the graphiql version.

I'm probably going to create a PR this weekend to bump the template to the 0.8 example.

**Comment by belohlavek** [comment]
@pelletiermaxime super weird, it now works for me too. Huh.

If anyone bumps into this in the future, a quick walkaround would be to change the url in the `vendor` files.

Thanks for the quick response!

**Comment by dmongeau** [comment]
I will still move the assets in the package because you are right that it should not rely on a service like unpkg.com that may not work in the future!
