### ISSUE TITLE
Question : How can I export or import schema.json

### ISSUE THREAD

**Issue by matart15** [Folkloreatelier/laravel-graphql#76]
Any way to import schema from json.

My front end developed separately. On development, front end uses graphql from node server. And I edit `schema.json`.

On production, backend need to be same schema. So currently I am re editing all php types and queries according to node server schema.json. basically doing same thing twice.

Is there any way to do it once on `schema.json` then reads to php OR write php then exports `schema.json`.
All i can think is json_encode/json_decode. But no idea where to start.

BTW: front end uses this library. https://github.com/lvarayut/relay-fullstack
JSON FILE: https://github.com/lvarayut/relay-fullstack/blob/master/server/data/schema.json

**Comment by dmongeau** [comment]
If you use the feature/relay branch, there is an artisan command for this:

```
php artisan graphql:schema
```
