### ISSUE TITLE
How to use in Lumen without Facades

### ISSUE THREAD

**Issue by 4levels** [Folkloreatelier/laravel-graphql#78]
Hi,

I currently have a Lumen API project and I don't want / need the use of Facades.  I'm fine with loading the correct classes when and where I need them.
This has worked good so far, including OAuth2, self written route middleware, Redis and a lot of queued jobs.

This library however throws fatal errors when `$app->withFacades()` is not set:

    FatalErrorException in GraphQLController.php L35
    Class 'Auth' not found

Can you provide instructions on how to use this library without Facades?

As soon as I enable facade support by uncommenting `$app->withFacades()` in `boostrap/app.php` everything works as expected.

Kind regards

**Comment by dmongeau** [comment]
@4levels Should be fixed now. Let me know if you have any issue
