### ISSUE TITLE
Integration with Lumen / Laravel 5.4

### ISSUE THREAD

**Issue by 4levels** [Folkloreatelier/laravel-graphql#79]
Hi,

are there any compatibility issues with this repo using Laravel or Lumen 5.4?
Currently the composer.json file doesn't mention 5.4 so composer fails to install.

Kind regards and keep up the great work!

**Comment by 4levels** [comment]
Hi,

I'm just from testing my clone of this repo with Lumen / Laravel 5.4 and everything seems to work just fine, including the scope & scopes middlewares from Laravel's Passport.

If you want I can create a PR from my fork, but all I did was add the 5.4 versions in composer.json

Kind regards,

Erik

**Comment by dmongeau** [comment]
Closing it, since your PR was merged
