### ISSUE TITLE
Minor documentation issues causing headaches - Lumen

### ISSUE THREAD

**Issue by 4levels** [Folkloreatelier/laravel-graphql#80]
Hi Devs,

when following the documentation, some uppercase-lowercase letters do make the difference!

When calling `GraphQL::type('User')` in the Query class, you have to add the type in graphql.php with Uppercase (not lowercase)

```
'types' => [
    'User' => 'App\GraphQL\Type\UserType'
]
```

Hope this helps someone save on painkillers ;-)

**Comment by dmongeau** [comment]
Fixed! Thanks!
