### ISSUE TITLE
Cannot use PHPUnit tests and Lumen with Facades

### ISSUE THREAD

**Issue by matheusmariano** [Folkloreatelier/laravel-graphql#81]
Hey there.

I'm building a project with Lumen and GraphQL and everything is working fine, except when I try to test with PHPUnit.

```
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 771 ms, Memory: 6.00MB

There was 1 error:

1) ExampleTest::testExample
ErrorException: Cannot declare class GraphQL, because the name is already in use

/var/www/vendor/folklore/graphql/src/Folklore/GraphQL/LumenServiceProvider.php:57
/var/www/vendor/folklore/graphql/src/Folklore/GraphQL/ServiceProvider.php:160
/var/www/vendor/laravel/lumen-framework/src/Application.php:172
/var/www/bootstrap/app.php:86
/var/www/tests/TestCase.php:12
/var/www/vendor/laravel/lumen-framework/src/Testing/TestCase.php:56
/var/www/vendor/laravel/lumen-framework/src/Testing/TestCase.php:67
```

It only works when I disable Facades.

**Comment by 4levels** [comment]
Hi @matheusmariano,

can you confirm the issue #78 I reported regarding Facades being required for this to work?
Or in other words, do you also need to enable Facades globally (in `bootstrap/app.php`) for this to work?

Kind regards,

**Comment by matheusmariano** [comment]
@4levels Yes, these issues are related. Unfortunately it's necessary to enable facades. Except when we're running tests, where GraphQL facade doesn't work.

The way I found to bypass this problem was disable the facades when the environment is `testing`.

```
if (env('APP_ENV') !== 'testing') {
    $app->withFacades();
}
```

Of course it's not a solution because it limit us to test GraphQL entities.

**Comment by 4levels** [comment]
Hi @matheusmariano,

Indeed, disabling Facades when running the tests is a workaround.
IMHO I'd rather not have Facades at all: I like to enable only what I need on a per-request basis instead of enabling all Facades with every time call.  I'm relying a lot on Jobs and Queues where I barely need any facade and so far my whole API works very good without Facades.

It's only this repo that requires me to use Facades, hence Issue #78 ;-)

I hope someone of Folkloreatlier can have a look at this..

**Comment by dmongeau** [comment]
@4levels Are you working with the feature/relay branch?

**Comment by 4levels** [comment]
Hi @dmongeau,

I have tried (see issue #82 ) but currenlty I reverted back to tag 1.0.8 (~1.0 in composer.json)

**Comment by dmongeau** [comment]
@4levels I've made an update (1.0.9) that should get rid of Facades. Can you see if it resolves the issue?

**Comment by dmongeau** [comment]
Can you confirm that this is resolved?

**Comment by 4levels** [comment]
Hi @dmongeau 

I'm currently unable to test this thouroughly, but I keep running into this error with Facades disabled:

    ErrorException: Argument 1 passed to Folklore\GraphQL\Console\PublishCommand::__construct() must be an instance of Illuminate\Filesystem\Filesystem, none given, called in /data/dev/projects/mancloud/api/vendor/folklore/graphql/src/Folklore/GraphQL/LumenServiceProvider.php on line 86 

When running with Facades (I'm not going to, but just to provide you feedback) I still get the same errors:

```
ErrorException: Cannot redeclare class GraphQL

/data/dev/projects/mancloud/api/vendor/folklore/graphql/src/Folklore/GraphQL/LumenServiceProvider.php:72
/data/dev/projects/mancloud/api/vendor/folklore/graphql/src/Folklore/GraphQL/ServiceProvider.php:151
/data/dev/projects/mancloud/api/vendor/laravel/lumen-framework/src/Application.php:172
/data/dev/projects/mancloud/api/bootstrap/app.php:111
/data/dev/projects/mancloud/api/tests/TestCase.php:12
/data/dev/projects/mancloud/api/tests/TestCase.php:28
/data/dev/projects/mancloud/api/vendor/laravel/lumen-framework/src/Testing/TestCase.php:67
```

It seems that the class_alias call in LumenServiceProvider is the culprit here, but that you pbbly already know ;-)

Thanks again for looking into this!

**Comment by 4levels** [comment]
As as problematic consequence, this error also causes eg. `php artisan migrate` to fail..

**Comment by dmongeau** [comment]
Thanks a lot for looking into this. I have fixed the error with PublishCommand. For the class_alias, I'm not really familiar with Lumen, how should we register a Facade in Lumen?

**Comment by dmongeau** [comment]
Ok I have removed the class_alias call from the LumenServiceProvider and instead it is explained in the Readme how to create the alias.

**Comment by neronmoon** [comment]
+1 here!
