### ISSUE TITLE
Make it compatible with Relay specification of Graph-ql 

### ISSUE THREAD

**Issue by mayankchd** [Folkloreatelier/laravel-graphql#9]
https://github.com/graphql/graphql-relay-js

https://facebook.github.io/relay/docs/graphql-relay-specification.html#content

**Comment by dmongeau** [comment]
Yes, I have planned to work on that.

**Comment by chiedojohn** [comment]
Any update on this?

**Comment by Gugudesaster** [comment]
Where is the problem with the implementation right now and can we help?
I haven't tried it yet, but I'm thinking of using it.
What has to be changed or has to be adapted?

**Comment by chiedojohn** [comment]
Thanks for being willing to help!
I've spent some time getting more familiar with graphql and relayjs and this task arguably should be its own repo.

For example, there is the main graphql repo on GitHub but then there is also this repo 
https://github.com/graphql/graphql-relay-js

The graphql-relay-js repo is more or less just a set of helpers to make it easier to write relayjs compliant code.

Graphql doesn't necessarily need to be RelayJS compliant so I'm actually thinking a separate repo called php-grahpql-relay or something with a set up helpers would make the most sense.

I've worked with laravel-graphql and it's pretty solid.

Just my two cents!

**Comment by dmongeau** [comment]
Hello,
I would love to add the helpers to make it compatible with Relay. For now it's just a problem of time on my side. I've looked into it and it's just a matter of implementing the Relay specs (or kind of adapt the graph-relay-js in PHP). You are free to do another repo if you feel like it, but I will be happy to merge a pull request in this repo. Also, there will be a couple of things that could be nice with laravel, like pagination.

If I was about to do it, I would honestly take the readme of graphql-relay-js and just implements all helpers listed there in a Relay folder of laravel-graphql.

Let me know, if someone is willing to try the implementation.

**Comment by chiedojohn** [comment]
Time's the issue on my side also. It was easier for me to just rebuild my backend in Node and use the existing tools. If I get a slow week/month though, I'll follow up here and work on it!

**Comment by soosap** [comment]
Would be sooo great to use it w/ Laravel. I am not a pro, but willing to test it and provide feedback.

**Comment by TimothyKrell** [comment]
Just found this today: https://github.com/nuwave/laravel-graphql-relay

Haven't had a chance to try it yet, but it looks useful.

**Comment by parweb** [comment]
any news on this ?

**Comment by dmongeau** [comment]
This is the next feature we will add. There is no ETA for this, but it should be soon (like in a month max). I'm open to pull request.

**Comment by sandervanhooft** [comment]
Perhaps also keep an eye out for [this project](https://github.com/nuwave/lighthouse).

**Comment by dmongeau** [comment]
The library is now compatible with Relay. You can check the branch feature/relay (https://github.com/Folkloreatelier/laravel-graphql/tree/feature/relay). The only thing missing is the documentation. I'm finishing it and will release this after. In the meantime, if someone would like to test it and give comments, would be really helpful. You can check in the fixture folder of the tests to see an example of an implementation of Relay.

Cheers

**Comment by matart15** [comment]
@dmongeau on `feature/relay` branch how can i set args on ConnectionType?.
I managed to get user connection on viewer type. Now this returns all users.
```
  viewer {
    users  {
      pageInfo {
        startCursor
      }
      edges {
        node {
          id
        }
      }
    }
  }
}

```

I tried get get first 5 user. then 5 to 10 like this.
```
  viewer {
    users(first: 5)  {
      pageInfo {
        startCursor
      }
      edges {
        node {
          id
        }
      }
    }
  }
}
```

I get this `Unknown argument \"first\" on field \"users\" of type \"viewer\".`

I tried using `ConnectionField`  but that gives me 
```
  viewer {
    email
    users  (first: 5){
      id
      email
    }
}
```

Not familiar with relay but looking [here](https://facebook.github.io/relay/docs/graphql-connections.html) it seems data should me this format right
```
 viewer {
   users   {
      pageInfo {
        startCursor
      }
      edges {
        node {
          id
          email
        }
      }
    }
}
```

**Comment by dmongeau** [comment]
The documentation is almost done here:
https://github.com/Folkloreatelier/laravel-graphql/blob/feature/relay/docs/relay.md
