### ISSUE TITLE
Auto camelCase to snake_case

### ISSUE THREAD

**Issue by odannyc** [Folkloreatelier/laravel-graphql#97]
I have snake_case column names in my database.

I want to query something like: `someThingCool` and have it automatically convert to fetch `some_thing_cool`.

Is this implemented already or is there a way to do this?

**Comment by dstollie** [comment]
Im looking for the exact same thing. Have you already found a nice solution?

**Comment by joshstar** [comment]
I have my models extend a BaseModel and include this:
```
public function toArray()
    {
        $array = parent::toArray();
        $arrayCamelCase = [];

        foreach($array as $key => $value) {
            $arrayCamelCase[camel_case($key)] = $value;
        }

        return $arrayCamelCase;
    }
```

**Comment by tremby** [comment]
Related to #112

**Comment by SonarSoftware** [comment]
I would say the approach implemented by @joshstar is the correct one. This is really an application specific function. Generally, I think it is a good approach for all your queries, types, mutations, etc, to extend from a base class that allows you to enforce these kinds of things.

**Comment by dmongeau** [comment]
Closing this since it can be fixed and I don't see why it should behave like that automatically
