### ISSUE TITLE
GraphiQL query variables don't seem to work

### ISSUE THREAD

**Issue by lokken** [Folkloreatelier/laravel-graphql#98]
When I use query variables in the GraphiQL editor, the variables do not end up in the $args argument of the Query::resolve method. However, if I hard-code the variable, they do show up.

### No worky!
```
query FetchThings($id: String) {
  things(id: $id) {
    thing_1,
    thing_2
  }
}

Query Variables
{
  "id": "2462346"
}
```

```
public function resolve($root, $args...) {
    Log::info(print_r($args, true)); 
    ...
}

[2017-03-15 15:28:31] lumen.INFO: Array
(
)
```

### It works!
```
query FetchThings {
  things(id: "2462346") {
    thing_1,
    thing_2
  }
}
```

```
public function resolve($root, $args...) {
    Log::info(print_r($args, true)); 
    ...
}

[2017-03-15 15:48:19] lumen.INFO: Array
(
    [id] => 2462346
)
```

**Comment by lokken** [comment]
Ah, the issue is ```'variables_input_name' => 'params',``` has to be changed to ```'variables_input_name' => 'variables',``` as is mentioned in the graphql.php config file.

**Comment by dmongeau** [comment]
Yes, actually `variables` will be default in the next version

**Comment by lokken** [comment]
Cool. Since you brought it up, when is the next version going to be released? :)
